### ISSUE TITLE
Include an example for Training from an SequenceInputFormat 

### ISSUE THREAD

**Issue by abhaymise** [yahoo/CaffeOnSpark#100]
Can you please provide an example to train from Hadoop SequenceFile.
As of now the examples included train from single-node file formats, such as LMDB.
It would be really nice to see an example from a distributed file format.

**Comment by junshi15** [comment]
There is an example for dataframe on this page:
https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_EC2

In my opinion, Spark dataframe is more powerful than Hadoop sequencefile.
