### ISSUE TITLE
use git clone, but caffe-public is empty

### ISSUE THREAD

**Issue by guchensmile** [yahoo/CaffeOnSpark#101]
Should I git clone git@github.com:BVLC/caffe.git and ln -s caffe  caffe-public?

By the way, I get error below:

CXX tools/caffe.cpp
CXX/LD -o .build_release/tools/caffe.bin
.build_release/tools/caffe.o: In function `train()':
caffe.cpp:(.text+0x1a1d): undefined reference to `caffe::P2PSync<float>::run(std::vector<int, std::allocator<int> > const&)'
.build_release/tools/caffe.o: In function `time()':
caffe.cpp:(.text+0x24ff): undefined reference to `void caffe::caffe_gpu_dot<float>(int, float const*, float const*, float*)'
collect2: error: ld returned 1 exit status
make[1]: *** [.build_release/tools/caffe.bin] Error 1
make[1]: Leaving directory `/home/zwl/tools/CaffeOnSpark/caffe-public'
export LD_LIBRARY_PATH="/home/y/lib64:/home/y/lib64/mkl/intel64:/home/zwl/tools/CaffeOnSpark/caffe-public/distribute/lib:/home/zwl/tools/CaffeOnSpark/caffe-distri/distribute/lib:/usr/lib64:/lib64 "; mvn -B package
[INFO] Scanning for projects...
...

How should I manage the caffe and CaffeOnSpark?

Best Regard.

**Comment by guchensmile** [comment]
Maybe I find what's wrong.

I get a wrong caffe branch from BVLC.

I will try git@github.com:yahoo/caffe.git.
It's really stupid question.

**Comment by junshi15** [comment]
If you try to build, use the instructions here:
https://github.com/yahoo/CaffeOnSpark/wiki/build

**Comment by guchensmile** [comment]
Thanks for you instructions.

I do as it, it's same error.
When I only clone  and build caffe, there is the same error:
.build_release/tools/caffe.o: In function `train()':
caffe.cpp:(.text+0x1a1d): undefined reference to `caffe::P2PSync<float>::run(std::vector<int, std::allocator<int> > const&)'
.build_release/tools/caffe.o: In function `time()':
caffe.cpp:(.text+0x24ff): undefined reference to `void caffe::caffe_gpu_dot<float>(int, float const*, float const*, float*)'
collect2: error: ld returned 1 exit status

I should fix the compiled error on caffe  firstly.
