### ISSUE TITLE
graphics memory used is 500 MB but Available is 4GB

### ISSUE THREAD

**Issue by abhaymise** [yahoo/CaffeOnSpark#103]
While training with my own data which is around 34 GB LMDB all resized to 224.
I am trying to run googlenet on the data.I notice two awkward things ==>

1. The complete 34 GB LMDB is getting copied in /tmp file first and then to the log directory of spark which means disk being used by the process becomes 3X the LMDB size.Most of the time goes in copying in these three locations.

2. When i fire a command to check graphics memory used by the training process i see it is using up only 500 MB leaving 3.5 GB unused which could have added in speed of processing.

I have a 2 node g2.2xlarge spark standalone cluster having 200 GB of storage attached to each with the source of data being HDFS.

Any suggestions to make optimum utilisation of the resources vailable

**Comment by junshi15** [comment]
1) don't use LMDB, use data frame instead so that the copy under /tmp will be avoided. LMDB is not a distributed file format.

2) try large batch size.

**Comment by abhaymise** [comment]
With DF this problem got resolved.
