### ISSUE TITLE
Rename 'Running CaffeOnSpark Locally' to 'Running CaffeOnSpark on standalone Spark cluster'

### ISSUE THREAD

**Issue by desertnaut** [yahoo/CaffeOnSpark#107]
The term 'locally' in the subject sections of the wiki is misleading: what is actually described is how to run CaffeOnSpark on a Spark standalone cluster, and not how to run locally (i.e. with ``--master local[]`` argument in ``spark-submit``). See [this part of Spark documentation](https://spark.apache.org/docs/1.6.0/submitting-applications.html) for justification.

**Comment by anfeng** [comment]
Good point. I Have fixed the documentations
