### ISSUE TITLE
Run with spark local model problem 

### ISSUE THREAD

**Issue by yamadi** [yahoo/CaffeOnSpark#113]
Hi ,
When I run the scrip:
spark-submit --master local\
    --files /home/caffeOnSpark/CaffeOnSpark/data/lenet_memory_solver.prototxt,/home/caffeOnSpark/CaffeOnSpark/data/lenet_memory_train_test.prototxt \
    --conf spark.cores.max=1 \
    --conf spark.task.cpus=1 \
    --conf spark.driver.extraLibraryPath="$LD_LIBRARY_PATH" \
    --conf spark.executorEnv.LD_LIBRARY_PATH="$LD_LIBRARY_PATH" \
    --class com.yahoo.ml.caffe.CaffeOnSpark  \
    /home/caffeOnSpark/CaffeOnSpark/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
        -train \
        -features accuracy,loss -label label \
        -conf lenet_memory_solver.prototxt \
    -clusterSize 1 \
        -devices 1 \
    -connection ethernet \
        -model file:/home/caffeOnSpark/CaffeOnSpark/mnist_lenet.model \
        -output file:/home/caffeOnSpark/CaffeOnSpark/lenet_features_result

It occur the problem:
Caused by: org.apache.spark.SparkException: File /tmp/spark-aa8bdf19-346e-49cf-bf0d-595896e5dc79/userFiles-285a8e4b-78bb-417a-9c9f-f5c5adaba6f8/mnist_train_lmdb exists and does not match contents of file:/home/caffeOnSpark/CaffeOnSpark/data/mnist_train_lmdb/

Can you help me ?

**Comment by junshi15** [comment]
maybe you need to delete the following file before launch it again?
 /tmp/spark-aa8bdf19-346e-49cf-bf0d-595896e5dc79/userFiles-285a8e4b-78bb-417a-9c9f-f5c5adaba6f8/mnist_train_lmdb

**Comment by yamadi** [comment]
I can't find the files.
