### ISSUE TITLE
LMDB entry's channels/height/width need to be reserved

### ISSUE THREAD

**Issue by anfeng** [yahoo/CaffeOnSpark#12]
Our current implementation maps LMDB's key/label/data nicely, but didn't include channels/height/width. The lost information will result certain use cases (see #10) to fail due to channel/width/height mismatch.

**Comment by rahulbhalerao001** [comment]
Could you please let know, the rough timeline for this. It will be helpful for planning.

**Comment by anfeng** [comment]
We plan to have a PR soon (this week).

**Comment by anfeng** [comment]
This issue is now closed with PR #17. The expanded [YARN GetStarted guide](https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_yarn) explains how cifar10 LMDB dataset is used.
