### ISSUE TITLE
Do you have any benchmark data?

### ISSUE THREAD

**Issue by swlsw** [yahoo/CaffeOnSpark#13]
I am wondering if there is any benchmark data about training time / num of machines.
(ex: ImageNet Training Time with 2 ~ N machines)

**Comment by anfeng** [comment]
We did a quick benchmark several months back. It will be nice to do that. 
See our early blog post: http://yahoohadoop.tumblr.com/post/129872361846/large-scale-distributed-deep-learning-on-hadoop
