### ISSUE TITLE
What happens if one executor fails in muti executors running mode.

### ISSUE THREAD

**Issue by JianboZhao** [yahoo/CaffeOnSpark#136]
hi, all
  I looked through the caffeOnSpark code, and found that every executor must sync each other for the data before mini-batch training. Does that means that if one of the executors fails, the training work will hang at the sync operation??

**Comment by junshi15** [comment]
training will fail if any executor fails.

**Comment by anfeng** [comment]
The job should not hang. Spark should declare the job failed.
You could then use the snapshot models to resume training.
