### ISSUE TITLE
Compile error with Spark 2.0

### ISSUE THREAD

**Issue by markyeh** [yahoo/CaffeOnSpark#149]
Hi,

I followed the README to compile CaffeOnSpark with Spark2.0.
$ mvn -Dspark.version=2.0.0 -Dhadoop.version=2.7.2 -Dscala.major.version=2.11 -Dscala.version=2.11.8 clean package

But I got the following errors. 
Any suggestion? thanks.

[INFO] ------------------------------------------------------------------------
[INFO] Building caffe-grid 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ caffe-grid ---
[INFO] Deleting /home/hadoop/package/CaffeOnSpark_2/caffe-grid/target
[INFO]
[INFO] --- maven-compiler-plugin:3.0:compile (compile-generator) @ caffe-grid ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 1 source file to /home/hadoop/package/CaffeOnSpark_2/caffe-grid/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ caffe-grid ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-scala-plugin:2.14.2:add-source (scala-compile-first) @ caffe-grid ---
[INFO] Add Source directory: /home/hadoop/package/CaffeOnSpark_2/caffe-grid/src/main/scala
[INFO] Add Test Source directory: /home/hadoop/package/CaffeOnSpark_2/caffe-grid/src/test/scala
[INFO]
[INFO] --- maven-scala-plugin:2.14.2:compile (scala-compile-first) @ caffe-grid ---
[INFO] Checking for multiple versions of scala
[WARNING]  Expected all dependencies to require Scala version: 2.11.8
[WARNING]  com.twitter:chill_2.11:0.8.0 requires scala version: 2.11.7
[WARNING] Multiple versions of scala libraries detected!
[INFO] includes = [**/*.scala,**/*.java,]
[INFO] excludes = []
[INFO] /home/hadoop/package/CaffeOnSpark_2/caffe-grid/src/main/java:-1: info: compiling
[INFO] /home/hadoop/package/CaffeOnSpark_2/caffe-grid/src/main/scala:-1: info: compiling
[INFO] Compiling 23 source files to /home/hadoop/package/CaffeOnSpark_2/caffe-grid/target/classes at 1473672367748
[ERROR] /home/hadoop/package/CaffeOnSpark_2/caffe-grid/src/main/scala/com/yahoo/ml/caffe/DataFrameSource.scala:108: error: missing parameter type
[INFO]     df.map(row => {
[INFO]            ^
[ERROR] one error found
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] caffe .............................................. SUCCESS [  0.138 s]
[INFO] caffe-distri ....................................... SUCCESS [05:30 min]
[INFO] caffe-grid ......................................... FAILURE [ 22.287 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:53 min
[INFO] Finished at: 2016-09-12T17:26:21+08:00
[INFO] Final Memory: 56M/1900M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scala-tools:maven-scala-plugin:2.14.2:compile (scala-compile-first) on project caffe-grid: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1(Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :caffe-grid

**Comment by junshi15** [comment]
Did Spark 1.6 work for you? We have not done extensive testing with spark 2.0.

**Comment by markyeh** [comment]
Yes, Spark 1.6 is fine for me.

**Comment by anfeng** [comment]
Pull request #153 has been created. Please try it out.

**Comment by markyeh** [comment]
This issue is fixed, thanks.
