### ISSUE TITLE
i use my images trained a caffemodel on CaffeOnSpark,and then ,i want to do predict,how should i do with CaffeOnSpark?? thanks a lot for response mo!

### ISSUE THREAD

**Issue by lklong** [yahoo/CaffeOnSpark#156]
thanks a lot! first ,i want to get features from predict_image and i don't use code like "cos.train(dl_train_source)" ,i want to use the caffemodel which i have trained before,and how shoud i load the caffemodel in my programme

**Comment by anfeng** [comment]
@lklong please continue the discussion on Issue #148.
