### ISSUE TITLE
Any thoughts into OpenStack Swift or Amazon S3 integration?

### ISSUE THREAD

**Issue by arundasan91** [yahoo/CaffeOnSpark#158]
Hello,

I am posting this here in hope of a discussion for an additional enhancement that may widen the scope of CaffeOnSpark by a bit. You guys are much more knowledgeable than me in this regard so here it goes.

For some of my deep-learning trainings, I used CaffeOnSpark and primarily used CIFAR10 and CIFAR100 datasets. I want to train a network on the ImageNet dataset now. However, my cloud baremetal instances have only 200GB disk space in them. ImageNet dataset itself is more than that size.

I looked for alternatives and found that I can distribute the entire dataset to HDFS from OpenStack Swift directly. I configured my hadoop cluster to work with OpenStack Swift. I was able to do `hadoop df -cp swift://<container_name>/<dataset> hdfs:///datasets/<dataset>` and copy datasets like CIFAR into HDFS. However, copying ImageNet requires `hadoop distcp` since while using `-cp`, my understanding is that, the file needs to be copied locally. (Correct me if I am wrong). The problem is that `distcp` is not working on my machine since the hadoop installation cannot find some java class that is required. I added the class to `classpath` but still giving me `java.lang.ClassNotFoundException:` error.

I was wondering if we can add a functionality in CaffeOnSpark to access datasets directly from OpenStack swift or Amazon S3 or the like; without downloading it locally on the machine. I wanted to try it out but thought of asking for opinions before jumping straight at it. Also, if I can get a direction on where to look at in CaffeOnSpark project, I could waste less time tampering the trivial stuff.

Thanks,
Arun

**Comment by arundasan91** [comment]
Update:

I was able to get `distCp` working in my environment. This means that I can copy files directly from OpenStack Swift to HDFS using some map-reduce operations without downloading the files locally.

This assures me that a similar functionality could possibly be added into  CaffeOnSpark.

Thanks,
Arun

**Comment by junshi15** [comment]
First of all, make sure you don't use lmdb for your dataset. that is not a distributed format. CaffeOnSpark copies the whole lmdb file to your local nodes. Try Spark data frame instead.

I have not used swift before, but from Spark doc: http://spark.apache.org/docs/latest/storage-openstack-swift.html, it is supported. You will need to rebuild CaffeOnSpark to include the dependency.

Once the rebuild is done, use swift:// in your prototxt file to specify the URL of the dataset, instead of using hdfs://

Let us know if that works for you.

**Comment by arundasan91** [comment]
Great thanks. I will try it out this week and will update back.

Thanks for the heads up.

**Comment by anfeng** [comment]
It will be great idea to extend CaffeOnSpark for additional storage, such as S3. Any interrest to provide a PR? We could guide you through the process.

**Comment by arundasan91** [comment]
Yes. Definitely. 

I would love to involve in this. I am a masters student and this is my final semester. Lots of work so to say. But I will keep this thread alive.

I looked into what @junshi15 suggested: 'will need to rebuild CaffeOnSpark to include the dependency' (swift + spark or S3 + spark). I suppose `CaffeOnSpark/caffe-grid/pom.xml` file is to be looked into initially.

**Comment by arundasan91** [comment]
Hello.

I configured the `core-site.xml` file in hadoop to work with OpenStack Swift. I created a YARN cluster. 

Verified working of Hadoop + Swift.

Rebuilt CaffeOnSpark.

Uploaded the CIFAR10 lmdb files to OpenStack Swift.

I went ahead and updated the prototxt files to point to swift.

Then I ran the example code given in the documentation.

I am actually getting some positive results. I think I am on the right track.

The VMs I have are slow. I'm spinning up a GPU instance now. Will update back soon.

Thanks.

**Comment by junshi15** [comment]
Great progress. Thanks for the update.

**Comment by arundasan91** [comment]
Update:

I can now use files in `Swift` object store directly in `Spark`. I was not able to get it working yesterday.

In spark-shell:
```
scala> val data = sc.textFile("swift://testcontainer.chameleoncloud/imagenet_label.txt")
data: org.apache.spark.rdd.RDD[String] = swift://testcontainer.chameleoncloud/imagenet_label.txt MapPartitionsRDD[1] at textFile at <console>:24

scala> data.count()
res1: Long = 21842
```

I am going to rebuild CaffeOnSpark now.
I have a doubt in using Spark DataFrame as an input as junshi15 suggested. Could someone please give a hint on how to do it ?
Thanks.

**Comment by arundasan91** [comment]
Update:

I successfully ran a training using `MNIST` dataset stored in Swift object storage and saved the model and output log to HDFS.

Please see the final configuration:

1. Hadoop version `2.7.1`, Spark version `2.0.1`
2. Updated Hadoop `core-site.xml` to add details regarding openstack swift. 
3. Made a new `core-site.xml` file in `$SPARK_HOME/conf/` with same values (no default FS tag).
4. Added `hadoop-openstack` dependency to `$CaffeOnSpark/caffe-grid/pom.xml`.
5. Confirmed working of `Hadoop + Swift` and `Spark + Swift`.
6. Built `CaffeOnSpark` with the new dependency.
7. Updated source file location in `$CaffeOnSpark/data/lenet_memory_train_test.prototxt` to `source: "swift://MNISTlmdb.chameleoncloud/mnist_train_lmdb"` and `source: "swift://MNISTlmdb.chameleoncloud/mnist_test_lmdb/"`
8. Ran the following command:

```
export SPARK_WORKER_INSTANCES=2 
export DEVICES=1
hadoop fs -rm -f hdfs:///mnist.model
hadoop fs -rm -r -f hdfs:///mnist_features_result
spark-submit --master yarn --deploy-mode cluster \
    --num-executors ${SPARK_WORKER_INSTANCES} \
    --files ${CAFFE_ON_SPARK}/data/lenet_memory_solver.prototxt,${CAFFE_ON_SPARK}/data/lenet_memory_train_test.prototxt \
    --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
    --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
    --class com.yahoo.ml.caffe.CaffeOnSpark  \
    ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
        -train \
        -features accuracy,loss -label label \
        -conf lenet_memory_solver.prototxt \
        -devices ${DEVICES} \
    -connection ethernet \
        -model hdfs:///mnist.model \
        -output hdfs:///mnist_features_result
```
`9. Confirmed by checking HDFS:

```
hadoop fs -ls hdfs:///mnist.model
hadoop fs -cat hdfs:///mnist_features_result/*
```

@anfeng , @junshi15 : Does this still mean that `CaffeOnSpark` is copying the entire `lmdb` file locally for training ? I could definitely look into `Spark dataframe` instead of `lmdb`. Any pointers ? Also, I do not have access to any `AWS` instances and `S3` object storage. In my understanding only the `core-site.xml` files need to be changed to use `S3` with Hadoop and Spark.

Shall I give a PR with these changes or additions ? Any suggestions on how to proceed with this ?

Thanks,
Arun

**Comment by anfeng** [comment]
@arundasan91 Great effort. Your LMDB files are copied from swift to local file system, per https://github.com/yahoo/CaffeOnSpark/blob/master/caffe-grid/src/main/scala/com/yahoo/ml/caffe/LmdbRDD.scala#L253-L257. For small dataset such as MNIST, I think this is acceptable solution.

Since your solution doesn't change any source code, you could either update our GetStarted guides or create a new one. 

Maybe, you want to share this approach on mailing list. Hopefully someone will confirm it with S3 storage.

**Comment by arundasan91** [comment]
Sure, Thanks. 
Will I have to write my own interfaces to use datasets as Spark Dataframe other than lmdb?

**Comment by anfeng** [comment]
You should be able to use the existing dataframe classes, such as ImageDataFrame. 
See https://github.com/yahoo/CaffeOnSpark/blob/master/data/lenet_dataframe_train_test.prototxt
You may only need to put scheme "swift://" for locations.

We have provided some tools for dataframe creation at https://github.com/yahoo/CaffeOnSpark/tree/master/caffe-grid/src/main/scala/com/yahoo/ml/caffe/tools.

**Comment by arundasan91** [comment]
Thanks. I will look into them.

**Comment by arundasan91** [comment]
Could you guys please look into this wiki page ? 

[GetStarted_yarn_object_storage](https://github.com/arundasan91/CaffeOnSpark/wiki/GetStarted_yarn_object_storage)

I wrote the entire steps which I required to create the environment ready. I have also requested a PR for the neccessary files.

Thanks.

**Comment by arundasan91** [comment]
Closing the Issue. Documentation added at [GetStarted_yarn_object_storage](https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_yarn_object_storage) for OpenStack Swift. Amazon S3 documentation to be added soon.
