### ISSUE TITLE
Wiki links for standalone (and standalone for OSX) are incorrect

### ISSUE THREAD

**Issue by praneetloke** [yahoo/CaffeOnSpark#159]
The correct links are https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_standalone and https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_standalone_osx.

**Comment by anfeng** [comment]
Thanks very much. It's now fixed.

**Comment by praneetloke** [comment]
I'll close this. Just looked at the wiki links again and looks good.
