### ISSUE TITLE
caffe-grid build failure

### ISSUE THREAD

**Issue by bikash119** [yahoo/CaffeOnSpark#163]
caffe-grid build fails on master branch 

ERROR] error: Class com.google.protobuf.GeneratedMessageV3 not found - continuing with a stub.
[ERROR] error: Unable to locate class corresponding to inner class entry for Builder in owner com.google.protobuf.GeneratedMessageV3
[ERROR] /Users/boredmgr/work/learn-spark/CaffeOnSpark/caffe-grid/src/main/scala/com/yahoo/ml/caffe/LmdbRDD.scala:137: error: overloaded method value mergeFrom with alternatives:
[INFO](x$1: caffe.Caffe.Datum)caffe.Caffe.Datum.Builder <and>
[INFO](x$1: com.google.protobuf.Message)caffe.Caffe.Datum.Builder
[INFO]  cannot be applied to (Array[Byte])
[INFO]           datum_bdr.mergeFrom(next.getValue())
[INFO]                     ^
[WARNING] 128 warnings found
[ERROR] 13 errors found
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] caffe .............................................. SUCCESS [  0.002 s]
[INFO] caffe-distri ....................................... SUCCESS [02:14 min]
[INFO] caffe-grid ......................................... FAILURE [07:18 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by arundasan91** [comment]
Hello,

Have you installed all the Caffe dependencies ?

What about `protobuf-compiler` ?

Could you please post the entire log as a pastebin or gist link ?

What is your JAVA version?

Thanks,
Arun

**Comment by mriduljain** [comment]
Closing this as there is no update. Please reopen if necessary
