### ISSUE TITLE
something wrong when buiding caffe-grid

### ISSUE THREAD

**Issue by jq460494839** [yahoo/CaffeOnSpark#175]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] caffe .............................................. SUCCESS [  0.001 s]
[INFO] caffe-distri ....................................... SUCCESS [13:04 min]
[INFO] caffe-grid ......................................... FAILURE [  02:24 h]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:39 h
[INFO] Finished at: 2016-11-01T08:57:52-07:00
[INFO] Final Memory: 27M/209M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project caffe-grid: Could not resolve dependencies for project com.yahoo.ml:caffe-grid:jar:0.1-SNAPSHOT: The following artifacts could not be resolved: org.apache.spark:spark-core_2.11:jar:2.0.0, io.netty:netty-all:jar:4.0.29.Final, io.netty:netty:jar:3.8.0.Final, io.dropwizard.metrics:metrics-core:jar:3.1.2: Could not transfer artifact org.apache.spark:spark-core_2.11:jar:2.0.0 from/to central (https://repo.maven.apache.org/maven2): GET request of: org/apache/spark/spark-core_2.11/2.0.0/spark-core_2.11-2.0.0.jar from central failed: Connection reset -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :caffe-grid
make: *** [build] Error 1

What shuold I do?

**Comment by junshi15** [comment]
It looks like you were not able to connect to maven repo and fetch spark-core_2.11-2.0.0.jar. I just checked the following URL is fine: 

https://repo.maven.apache.org/maven2/org/apache/spark/spark-core_2.11/2.0.0/spark-core_2.11-2.0.0.jar
 
maybe you had network outage?

**Comment by jq460494839** [comment]
maybe you are right 
make clean 
make build
it work now

**Comment by jq460494839** [comment]
i didn't make caffe-public before...
