### ISSUE TITLE
How to use Intellij idea to build the CaffeOnSpark?

### ISSUE THREAD

**Issue by liuguiyangnwpu** [yahoo/CaffeOnSpark#179]
hi,
I want to use Intellji idea to build the CaffeOnSpark? 
By the way, the cluster can't connect to the internet !
I can download the maven packages into the local !

thx !

**Comment by junshi15** [comment]
CaffeOnSpark is a mixture of C++, Java, Python, Scala. I am not sure IntelliJ is able to handle the mixture properly.

**Comment by mriduljain** [comment]
Install the respective plugins. First build the complete project on command
line and import as maven project. I use it for Scala Java atleast

**Comment by liuguiyangnwpu** [comment]
I will try it !
thx @junshi15  @mriduljain
