### ISSUE TITLE
how to understand the output features

### ISSUE THREAD

**Issue by xiaojimi** [yahoo/CaffeOnSpark#180]
I thought features are reflections of acc rate in the first place. Since the output feature from  minist and cifar10 test are not convergent, I can not consicely understand the realation between **acc rate and features**. I went through Object **CaffeOnspark**, but still retaining confusions.

**Comment by xiaojimi** [comment]
I used spark on yarn and  performed the test template spark submit scripts in tutorial.

**Comment by junshi15** [comment]
Features are just layer outputs (probes). A feature does not have to be accuracy, it can be any layer output from the network. For the example in https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_EC2 (section 3), we have "-features accuracy,loss", meaning we want to output "accuracy" and "loss" from the network.

**Comment by xiaojimi** [comment]
thanks a lot. It helps a lot.
