### ISSUE TITLE
Should I install caffeonspark to all the slave node ?

### ISSUE THREAD

**Issue by liuguiyangnwpu** [yahoo/CaffeOnSpark#181]

**Comment by junshi15** [comment]
slave nodes need caffeonspark too. you can either install it individually, or use "--archives" option of "spark-submit" to ship it from the launch box.

**Comment by liuguiyangnwpu** [comment]
Hi,

I am so sorry to bother you.
I want to push the CafefOnSpark to HDFS, so that all the slaves and masters can use Only One Copy of CaffeOnSpark Configuration Files.
Which libs should I push to the HDFS ?

thx !
