### ISSUE TITLE
How to test in the yarn cluster

### ISSUE THREAD

**Issue by jjang20207** [yahoo/CaffeOnSpark#182]
Hi, i'm jason.

Thank you for all contributors of this project.

I'm wondering how to test a single image(jpg) after creating the model in CaffeOnSpark.

I followed the user guide for training and did it successfully.

But, I cant find any information about testing in the cluster.

I want to test only a jpg file without converting a lmdb or leveldb file.

Can anyone give me an answer?

Thanks in advance.

**Comment by xiaojimi** [comment]
#148 will help you.

**Comment by mriduljain** [comment]
Closing this. Please reopen if necessary
