### ISSUE TITLE
Image_net data didn't work

### ISSUE THREAD

**Issue by xiaojimi** [yahoo/CaffeOnSpark#186]
I can test ciffar10 and mnist data using CaffeOnSpark. When I gave a test on image_net data(LMDB format), the application on yarn could finish adding executor procedure. Then the application just got stuck and would not go any further. 
[imagenet.prototxt.txt](https://github.com/yahoo/CaffeOnSpark/files/588683/imagenet.prototxt.txt)
[imagenet_solver.prototxt.txt](https://github.com/yahoo/CaffeOnSpark/files/588682/imagenet_solver.prototxt.txt)
**this is my spark submit script:**
export SPARK_WORKER_INSTANCES=10
export DEVICES=1

hadoop fs -rm -f hdfs:///data/alexnet_muti/models/alexnet_model.model.h5
hadoop fs -rm -r -f hdfs:///data/alexnet_muti/models/result/
spark-submit --master  yarn --deploy-mode cluster \
    --num-executors ${SPARK_WORKER_INSTANCES} \
    --executor-memory 40G --driver-cores 3 --driver-memory 100G \
    --files /data/clusterserver/CaffeOnSpark/data/imagenet_solver.prototxt,/data/clusterserver/CaffeOnSpark/data/imagenet.prototxt,/data/clusterserver/CaffeOnSpark/data/imagenet_mean.binaryproto \
    --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
    --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
    --class com.yahoo.ml.caffe.CaffeOnSpark  \
    /data/clusterserver/CaffeOnSpark/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
        -train \
        -features accuracy, loss -label label  \
        -conf imagenet_solver.prototxt \
    -connection ethernet \
        -model hdfs:///data/alexnet_muti/models/alexnet_model.model.h5 \
        -output hdfs:///data/alexnet_muti/models/result/
hadoop fs -ls hdfs:///data/alexnet_muti/models/alexnet_model.model.h5
hadoop fs -cat hdfs:///data/alexnet_muti/models/result/*
**this is the  Diagnostic on yarn UI :**
Shutdown hook called before final status was reported.

I did have went through logs of this application. But nothing helped.
**this is  my logs by driver** : 

SLF4J: Found binding in [jar:file:/data/clusterdata/hadoop/nodemanager/yarn/local/usercache/root/filecache/17/spark-assembly-1.6.1-hadoop2.6.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/data/clusterserver/hadoop-2.6.4/share/hadoop/common/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
16/11/14 15:29:00 ERROR ApplicationMaster: RECEIVED SIGNAL 15: SIGTERM
^@^Fstdout^@^A0^@^A^@^@^D^@
        ^@^GVERSION*(^@&container_1479107705502_0006_01_000001^D^Dnone^A^PΞMΞM^C^Qdata:BCFile.index^DnoneΙ^K^K^Pdata:TFile.index^Dnoneͣ66^Odata:TFile.mett
a^DnoneΞ]^F^F^@^@^@^@^@^@^Cd^@^A^@^@ОQҨ~Qµ׶9ށ@~Rº

**Comment by junshi15** [comment]
Does it work if you disable the test by setting the following to zero.
test_iter: 0
test_interval: 0

While the program was stuck, you can use Spark UI to check which line the program was stuck at. That should help debug.

**Comment by xiaojimi** [comment]
@junshi15 thank you Shi. when I adjusted test_iter and test_interval to 0. The application did move forward to **collect section** as the screen shot illustrated. However, the application got stuck again : 
![qq 20161115113422](https://cloud.githubusercontent.com/assets/10665385/20292342/cc95c248-ab27-11e6-90f8-cac679a02cb1.jpg)

**Comment by liuguiyangnwpu** [comment]
@xiaojimi 您是如何如何CaffeOnSpark的，是要将CaffeOnSpark布置在每个节点，还是通过HDFS使得所有节点共享一份CaffeOnSpark，我不是很清楚该把CaffeOnSpark中的那些部分的库或者包放置在HDFS中！
希望您指导！

**Comment by xiaojimi** [comment]
@liuguiyangnwpu depends on what kind of platform your  applications run on. I am using Spark on yarn.  Hence, I referred  to Wiki step by step: https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_yarn.  In the first place, you should make sure that every machine in your cluster was properly installed with Caffe dependencies.

**Comment by liuguiyangnwpu** [comment]
@xiaojimi 
thank you for your response !

I installed CaffeOnSpark On the master node, and install caffe on the other slaves(NOT CaffeOnSpark)?
Is That Right ?

thx

**Comment by xiaojimi** [comment]
@liuguiyangnwpu   caffe prerequists(e.g. BLAS)

**Comment by junshi15** [comment]
@xiaojimi Line 154 and 123 are at the very beginning of the run. It seems to me there is some kind of Spark configuration issue. Can you reduce the number of executors to 1 or 2?
To check where the job hangs, you can click on "Exectuors" tab on the Spark GUI, then click "Dump Threads" on one of the executors, you will see lots of threads, find the ones that are in "wait" stage and are relevant to CaffeOnSpark. By examining the threads, we can get a better understanding of the problem.

**Comment by liuguiyangnwpu** [comment]
@xiaojimi , Thank you for your reply !
In other words, I should install caffe and caffe's environment on the other slaves, and Install CaffeOnSpark On master node, then use spark-submit to push my caffe job.
I will try this method in some days, If It occurs  some troubles during this stage, I will ask for your help !

thx !

**Comment by xiaojimi** [comment]
@junshi15 I shrink my executors to 2.

**Comment by junshi15** [comment]
The waiting threads you found may or may not be the cause. The synchronization between data RDD and Caffe solver is via blocking queues, like the producer-consumer model. The samples are read from RDD and put in the blocking queue and the caffe solver reads from the queue. The producer always feeds the samples unless the consumer tells it to stop, at which point, the program finishes. If for some reason the producer stop feeding the queue, but the consumer is expecting new samples, the program will hang.

**Comment by xiaojimi** [comment]
@junshi15  To my understanding, Spark just plays a role of storage in CaffeOnSpark. I will check if the producer had stop trucking data to the blocking queues. Any tips for checking?

**Comment by junshi15** [comment]
Actual, there are two blocking queues, i.e. RDD-->Transformer-->Caffe Solver, where "-->" is a blocking queue. Debug is not trivial. BTW, are you able to run any training? MNIST?

**Comment by xiaojimi** [comment]
@junshi15 Both cifar10 and mnist run trainning as expected. ImageNet bother me quite a while.

**Comment by junshi15** [comment]
@xiaojimi In that case, I think nothing is wrong. I assume your imagenet train lmdb is a very large file, which takes a lot of time to process (to form RDD). Just to test the idea, you can build a small train lmdb from the train images, say 100MB. Then the training should work just fine. We discourage the use of lmdb with CaffeOnSpark, since it is not suitable for distributed computing. We recommend either sequence files or  even better, data frame files for large datasets.

**Comment by xiaojimi** [comment]
@junshi15 I'll try dataframe

**Comment by xiaojimi** [comment]
@junshi15 how can I set **lmdb_partitions**. For now, my lmdb data is a single big file. My convert application also got stuck. I consider this un-partitioned lmdb file is the root causal reason to all my applications on CaffeOnSpark, Both the training application and the  convert application.

**Comment by xiaojimi** [comment]
@junshi15 I convert ilsvrc12_val_lmdb which size is 9.3G to parquet file saving in hdfs. However, when train the parquet files. application throw an error:
![qq 20161117152226](https://cloud.githubusercontent.com/assets/10665385/20379910/ae832706-acd9-11e6-9d86-d164cb8363f2.jpg)

**Comment by junshi15** [comment]
I would not use lmdb for file of size 200+GB. The implementation of lmdb for spark is kind of hack. the lmdb files need to be shipped to individual nodes. Since lmdb is not a distributed file format, it is not a good candidate for distributed training.

**Comment by junshi15** [comment]
Here is an example for how to use data frame in the prototxt:
https://github.com/yahoo/CaffeOnSpark/blob/master/data/lrcn_cos.prototxt
https://github.com/yahoo/CaffeOnSpark/blob/master/data/lrcn_solver.prototxt

**Comment by xiaojimi** [comment]
@junshi15 I have fixed the nullpointer problem by adjusting transform parameters in the net prototxt file. My applications are all fired up this afternoon. 
thanks.

**Comment by haikuoyao** [comment]
Hi  @xiaojimi I'm on the same boat with you. I tried to use 200G LMDB to train net however it didn't work. Seems there's a memory issue while it works great when I just used Caffe on local.

How did you solve this issue ? Did you convert LMDB to dataframe ? 

Thanks.

**Comment by xiaojimi** [comment]
@haikuoyao I solved this issue by using dataframe suggested by junshi15. Just do not use lmdb for training big datasets. Because this approach ships the whole lmdb file to all of your executors.

**Comment by haikuoyao** [comment]
Thanks @xiaojimi . Did you meet any issue when converting LMDB to data frame? I tried once but it failed. I'll try one more time though. 
Thanks a million.

**Comment by haikuoyao** [comment]
Thanks @xiaojimi . It works finally. A huge disk is needed on servers when converting LMDB to DataFrame.  :)  Then I trained on DataFrame. It works well. Thanks again.
