### ISSUE TITLE
how to save Caffe::Net  parameters in Spark?   have other way?

### ISSUE THREAD

**Issue by chris0927** [yahoo/CaffeOnSpark#188]
I have a Net which have trained well,how to  initialize Caffe::NET parameters and save it in Spark?  Like this:

initNet()  //only once

net->predict()  //use check image many times

**Comment by junshi15** [comment]
you can use "-weights your_model_file_path" to specify your model and "-test" to start prediction.

the command line will be like:

spark-submit --xxxxxxx \
--class com.yahoo.ml.caffe.CaffeOnSpark \
${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
-test \
-config your_solver.prototxt \
-weights your_model_file \
-xxxx

**Comment by chris0927** [comment]
how to add my image?

**Comment by chris0927** [comment]
@junshi15  how to add my image?

**Comment by chris0927** [comment]
@junshi15  how to use the test image?

**Comment by junshi15** [comment]
test images are specified in the prototxt file, e.g.
https://github.com/yahoo/CaffeOnSpark/blob/master/data/lenet_dataframe_train_test.prototxt#L33

**Comment by chris0927** [comment]
@junshi15  I capture from the camera, get JPG image, and then out, 15 frames every second , feeling the way of specified in the prototxt file is not appropriate.

**Comment by chris0927** [comment]
I capture from the camera, get JPG image, and then out, 15 frames every second .I need test in realtime.
If data is type: "MemoryData",I want to update data by MemoryDataLayer's AddMatVector and Reset.
How to do this?
Do CaffeOnSpark only make train well,not support test  in  realtime?

**Comment by chris0927** [comment]
@junshi15 
I capture from the camera, get JPG image,15 frames every second .I need test in realtime.
If data is type: "MemoryData",I want to update data by MemoryDataLayer's AddMatVector and Reset.
How to do this?
Do CaffeOnSpark only make train well,not support test in realtime?

**Comment by chris0927** [comment]
@junshi15  I find we can get image by parameter "-input",but not an example,the code:

 conf = SparkConf()
  sc = SparkContext(conf=conf)
  sqlContext = SQLContext(sc)
  cmdargs = conf.get('spark.pythonargs')
  parser = argparse.ArgumentParser(description="Image to Caption Util")
  parser.add_argument('-input', action="store", dest="input")
  parser.add_argument('-model', action="store", dest="model")
  parser.add_argument('-imagenet', action="store", dest="imagenet")
  parser.add_argument('-lstmnet', action="store", dest="lstmnet")
  parser.add_argument('-vocab', action="store", dest="vocab")
  parser.add_argument('-output', action="store", dest="output")
  
  args=parser.parse_args(cmdargs.split(" "))

  df_input = sqlContext.read.parquet(str(args.input))
  images = df_input.select("data.image","data.height", "data.width", "id")
  df=get_predictions(sqlContext, images, str(args.model), str(args.imagenet), str(args.lstmnet), str(args.vocab))
  df.write.json(str(args.output))

**Comment by junshi15** [comment]
there is no -input option for CaffeOnSpark. However, you could write your owner wrapper. The example you showed does exactly that. The following file shows under-the-hood details.

https://github.com/yahoo/CaffeOnSpark/blob/master/caffe-grid/src/main/python/examples/coco/captioner.py
If you read the header, it is based on Jeff Donahue's CoCo caption generation code.
