### ISSUE TITLE
source_class problem

### ISSUE THREAD

**Issue by xiaojimi** [yahoo/CaffeOnSpark#190]
@junshi15 I used LMDB2DataFrame.scala tool to convert my LMDB to ImageDataFrame saving in hdfs with parquet format. 
![qq 20161118134857](https://cloud.githubusercontent.com/assets/10665385/20420585/b9a86b26-ad99-11e6-873b-12c72aa9655e.jpg)

I really want to know what the difference of ImageDataFrame and DataframeSource. Especially, how to choose between these two formats.

**Comment by junshi15** [comment]
In your data frame above, encoded column may be wrong. If the images are JPEG, GIF, etc, they are encoded, if the images are raw bits, like MNIST, then encoded is false.

ImageDataFrame is an old and single format, it hard-coded the column names, each column has a rigid format, For example, label has to be a single integer. DataframeSource supplants ImageDataFrame. It is more versatile, for example, you can have a float-array as the label (this is useful if you want to the net to identify objects in a picture). I would encourage you to try out Dataframesource.

More info can be found here:
proto definition:
https://github.com/yahoo/caffe/blob/master/src/caffe/proto/caffe.proto#L1409-L1452

example proto:
https://github.com/yahoo/CaffeOnSpark/blob/master/data/lrcn_cos.prototxt#L20-L70

source code:
https://github.com/yahoo/CaffeOnSpark/blob/master/caffe-grid/src/main/scala/com/yahoo/ml/caffe/DataFrameSource.scala

conversion example for coco dataset.
https://github.com/yahoo/CaffeOnSpark/blob/master/caffe-grid/src/main/scala/com/yahoo/ml/caffe/tools/Conversions.scala

**Comment by xiaojimi** [comment]
@junshi15 https://github.com/yahoo/CaffeOnSpark/blob/master/caffe-grid/src/main/scala/com/yahoo/ml/caffe/tools/LMDB2DataFrame.scala
My data frame above is results of this tool. Did I use the wrong tool.
Thank you for these info provided above.

**Comment by junshi15** [comment]
The tool is fine, it copies "encoded" field from lmdb file. So you lmdb file has raw images instead of JPEGs?

**Comment by xiaojimi** [comment]
@junshi15  yes, raw images in my LMDB file.
