### ISSUE TITLE
what is caffeonsparkpythonapi.zip in Python for CaffeOnSpark

### ISSUE THREAD

**Issue by chris0927** [yahoo/CaffeOnSpark#192]
--py-files ${CAFFE_ON_SPARK}/caffe-grid/target/caffeonsparkpythonapi.zip

**Comment by junshi15** [comment]
This is for all the python api's. If you are using python to call CaffeOnSpark, you will need it. If you use scala, then you don't need it.

**Comment by chris0927** [comment]
@junshi15 The file I downloaded have not caffeonsparkpythonapi.zip,how to get it?

**Comment by junshi15** [comment]
did you compile the source file? The zip file is build by the line below:
https://github.com/yahoo/CaffeOnSpark/blob/master/Makefile#L25

**Comment by chris0927** [comment]
@junshi15 I didn`t find  it ,maybe I need make build again.

**Comment by mriduljain** [comment]
Did you manage to get it working ?

**Comment by chris0927** [comment]
@mriduljain  yes!
