### ISSUE TITLE
python spark submit error:DataFrame' object has no attribute 'map'

### ISSUE THREAD

**Issue by chris0927** [yahoo/CaffeOnSpark#193]
when I  run CaffeOnSpark/caffe-grid/target/examples/MultiClassLogisticRegression.py,have an error:
File "/usr/local/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 844, in __getattr__
AttributeError: 'DataFrame' object has no attribute 'map'

**Comment by chris0927** [comment]
Script:

spark-submit  --master ${MASTER_URL} \
          --driver-library-path "${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar" \
          --driver-class-path "${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar" \
          --conf spark.cores.max=${TOTAL_CORES} \
          --conf spark.task.cpus=${CORES_PER_WORKER} \
          --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
          --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
          --py-files ${CAFFE_ON_SPARK}/caffe-grid/target/caffeonsparkpythonapi.zip \
          --files ${CAFFE_ON_SPARK}/caffe-grid/target/caffe/_caffe.so,${CAFFE_ON_SPARK}/data/lenet_memory_solver.prototxt,${CAFFE_ON_SPARK}/data/lenet_memory_train_test.prototxt \
          --jars "${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar" \
          --conf spark.pythonargs="-conf lenet_memory_solver.prototxt -model file:///${CAFFE_ON_SPARK}/mnist_lenet.model -features accuracy,ip1,ip2 -label label -output file:///${CAFFE_ON_SPARK}/tmp/output -devices 1 -outputFormat json -clusterSize ${SPARK_WORKER_INSTANCES}" \
        ${CAFFE_ON_SPARK}/caffe-grid/target/examples/MultiClassLogisticRegression.py

**Comment by chris0927** [comment]
use .rdd.map, the reason is:
.rdd.map(...)
DataFrame.map has been removed in Spark 2.

**Comment by junshi15** [comment]
Thanks for reporting, we will take a look next week.

**Comment by mriduljain** [comment]
Thanks for reporting, will send a patch soon for spark 2
