### ISSUE TITLE
About  caffe of  other version?

### ISSUE THREAD

**Issue by chris0927** [yahoo/CaffeOnSpark#194]
I need  to use other version's caffe,could I replace the caffe-public of CaffeOnSpark and then make build? what should I do?

**Comment by junshi15** [comment]
A few BVLC caffe files are adapted for CaffeOnSpark, mostly in memory data layer. The current caffe-public is based on BVLC caffe commit 50c9a0fc8eed0101657e9f8da164d88f66242aeb

You can compare them to find where the files differ. Most likely, you just need to get the desired version of BVLC caffe, add/modify those files, and replace caffe-public with your BVLC caffe code.
