### ISSUE TITLE
Build Error ‘CoSDataParameter’ does not name a type

### ISSUE THREAD

**Issue by vijayg78** [yahoo/CaffeOnSpark#195]
Hi,
While building CoffeOnSpark on ubuntu i am getting the below error. What might be the issue?

cd caffe-public; make proto; make -j4 -e distribute; cd ..
make[1]: Entering directory `/home/rajesh/CaffeOnSpark/caffe-public'
make[1]: Nothing to be done for `proto'.
make[1]: Leaving directory `/home/rajesh/CaffeOnSpark/caffe-public'
make[1]: Entering directory `/home/rajesh/CaffeOnSpark/caffe-public'
CXX/LD -o .build_release/examples/cpp_classification/classification.bin
make[1]: Leaving directory `/home/rajesh/CaffeOnSpark/caffe-public'
export LD_LIBRARY_PATH="/home/y/lib64:/home/y/lib64/mkl/intel64:/usr/local/cuda/:/home/rajesh/CaffeOnSpark/caffe-public/distribute/lib:/home/rajesh/CaffeOnSpark/caffe-distri/distribute/lib:/usr/lib64:/lib64 "; GLOG_minloglevel=1 mvn  -B package -DskipTests
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.yahoo.ml:caffe-grid:jar:0.1-SNAPSHOT
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] caffe
[INFO] caffe-distri
[INFO] caffe-grid
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building caffe 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building caffe-distri 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (proto) @ caffe-distri ---
[INFO] Executing tasks

protoc:
     [exec] make[1]: Entering directory `/home/rajesh/CaffeOnSpark/caffe-distri'
     [exec] make[1]: Nothing to be done for `proto'.
     [exec] make[1]: Leaving directory `/home/rajesh/CaffeOnSpark/caffe-distri'
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (compile-generator) @ caffe-distri ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ caffe-distri ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/rajesh/CaffeOnSpark/caffe-distri/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ caffe-distri ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (make) @ caffe-distri ---
[INFO] Executing tasks

make:
     [exec] make[1]: Entering directory `/home/rajesh/CaffeOnSpark/caffe-distri'
     [exec] CXX src/main/cpp/cos_data_layer.cpp
     [exec] make[1]: *** [.build_release/src/main/cpp/cos_data_layer.o] Error 1
     [exec] src/main/cpp/cos_data_layer.cpp: In member function ‘virtual void caffe::CoSDataLayer<Dtype>::LayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&)’:
     [exec] src/main/cpp/cos_data_layer.cpp:14:9: error: ‘CoSDataParameter’ does not name a type
     [exec]    const CoSDataParameter& cos_data_param = this->layer_param_.cos_data_param();
     [exec]          ^
     [exec] src/main/cpp/cos_data_layer.cpp:15:17: error: ‘cos_data_param’ was not declared in this scope
     [exec]    batch_size_ = cos_data_param.batch_size();
     [exec]                  ^
     [exec] make[1]: Leaving directory `/home/rajesh/CaffeOnSpark/caffe-distri'
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] caffe ............................................. SUCCESS [0.003s]
[INFO] caffe-distri ...................................... FAILURE [2.736s]
[INFO] caffe-grid ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.030s
[INFO] Finished at: Wed Nov 23 14:41:00 IST 2016
[INFO] Final Memory: 8M/147M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (make) on project caffe-distri: An Ant BuildException has occured: exec returned: 2
[ERROR] around Ant part ...<exec dir="/home/rajesh/CaffeOnSpark/caffe-distri" executable="make" failonerror="true">... @ 5:91 in /home/rajesh/CaffeOnSpark/caffe-distri/target/antrun/build-make.xml
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :caffe-distri

**Comment by junshi15** [comment]
It looks like your caffe-public directory is out-dated.

**Comment by vijayg78** [comment]
Don't think so, see the caffe-public git status. This is the latest version.

<prompt>:~/CaffeOnSpark/caffe-public$ git status
HEAD detached at fc0a02e
nothing to commit, working directory clean

**Comment by junshi15** [comment]
Then CosDataParameter is defined here:
https://github.com/yahoo/caffe/blob/fc0a02efd720bdc29b2f1d93e5354f19a2b9d559/src/caffe/proto/caffe.proto#L1409-L1452

Not sure why your log says " make[1]: Nothing to be done for proto"
Did you build your source code from scratch? i.e. git clone --recursive, etc?

**Comment by vijayg78** [comment]
Thanks for the hints, did a fresh pull (into another folder) and did the build process again. The build was successful!! Thanks a lot for the help.

**Comment by mriduljain** [comment]
closing this assuming everything works. Please reopen if necessary
