### ISSUE TITLE
libprotobuf ERROR google/protobuf/text_format.cc

### ISSUE THREAD

**Issue by chris0927** [yahoo/CaffeOnSpark#198]
I use protobuf2.5

------------------------------------------------------

 T E S T S
-------------------------------------------------------
Running TestSuite
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@5d22bbb7
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 17:15: Message type "caffe.LayerParameter" has no field named "source_class".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1128 14:22:25.588124 143832 upgrade_proto.cpp:68] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: src/test/resources/caffenet_train_net.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by junshi15** [comment]
Did you modify the caffe-public code? "source_class" is right here. I don't know why your program was not able to find it.

https://github.com/yahoo/caffe/blob/fc0a02efd720bdc29b2f1d93e5354f19a2b9d559/src/caffe/proto/caffe.proto#L355

**Comment by mriduljain** [comment]
Most probably there is a typo at line 17 column 15 in src/test/resources/caffenet_train_net.prototxt. Please paste this file if you can for us to see.

**Comment by chris0927** [comment]
Now there is not the error.I don`t know the reason.
