### ISSUE TITLE
I can't package jar after compile caffe...

### ISSUE THREAD

**Issue by xiangqiaolxq** [yahoo/CaffeOnSpark#2]
I can't package jar after compile caffe 
I can see these message 
export LD_LIBRARY_PATH="/usr/local/caffe-parallel-master/build/lib::/home/xiangqiao.lxq/CaffeOnSpark/caffe-public/distribute/lib:/home/xiangqiao.lxq/CaffeOnSpark/caffe-distri/distribute/lib:/usr/lib64:/lib64 "; mvn package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.yahoo.ml:caffe-grid:jar:0.1-SNAPSHOT
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/xiangqiao.lxq/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[78,23] caffe.Caffe.BlobShape is not abstract and does not override abstract method newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent) in com.google.protobuf.GeneratedMessage
[ERROR] /home/xiangqiao.lxq/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[236,25] caffe.Caffe.BlobShape.Builder is not abstract and does not override abstract method internalGetFieldAccessorTable() in com.google.protobuf.GeneratedMessage.Builder
[ERROR] /home/xiangqiao.lxq/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[414,23] caffe.Caffe.BlobProto is not abstract and does not override abstract method newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent) in com.google.protobuf.GeneratedMessage

I don't know how this happened，can anyone help me ?

**Comment by mriduljain** [comment]
What is the protobuf version and the platform (linux/osx)?

**Comment by mriduljain** [comment]
Please use protobuf 2.5.0. Check:
protoc --version

**Comment by xiangqiaolxq** [comment]
This problem is not about protoc version.
Because I can't compile caffe's python interface lead to can't create some file in cafffe-public/distribute.
Some files is needed by maven package...After I compile python interface by self this problem solved.
But some new issues happened...
[INFO] caffe .............................................. SUCCESS [  0.001 s]
[INFO] caffe-distri ....................................... FAILURE [  3.712 s]
[INFO] caffe-grid ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.949 s
[INFO] Finished at: 2016-02-26T02:03:29-05:00
[INFO] Final Memory: 20M/1215M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (compile-generator) on project caffe-distri: Compilation failure: Compilation failure:
[ERROR] /home/xiangqiao.lxq/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[9919,31] cannot find symbol
[ERROR] symbol:   class ProtocolStringList
[ERROR] location: package com.google.protobuf
[ERROR] /home/xiangqiao.lxq/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[8280,24] cannot find symbol
[ERROR] symbol:   class ProtocolStringList
 Is protobuf not right ?

**Comment by mriduljain** [comment]
Via protoc just wanted to find protobuf version installed.

**Comment by mriduljain** [comment]
your .proto files compiled via protoc and the protobuf version mentioned in the pom should match

**Comment by junshi15** [comment]
It sounds like protobuf version mismatch. You probably have protobuf-2.6+ installed. but caffe-distri/pom.xml needs 2.5.
https://github.com/yahoo/CaffeOnSpark/blob/master/caffe-distri/pom.xml#L27
Please check your protobuf version by "protoc --version"

Also, python interface is not needed for current CaffeOnSpark to work. You can disable the python option in the makefile.

**Comment by xiangqiaolxq** [comment]
Yeah, my protobuf is 2.6...
After I reinstall protobuf 2.5 ,all things is ok~
