### ISSUE TITLE
How to use CaffeOnSpark?

### ISSUE THREAD

**Issue by guody5** [yahoo/CaffeOnSpark#200]
I have made build successfully.But I don't know how to use it.So I look for documentation,but I don't find it.
Could someone give me some materials,webs or examples to use it?

**Comment by chris0927** [comment]
https://github.com/yahoo/CaffeOnSpark/wiki

**Comment by mriduljain** [comment]
Could you please close this if you were able to get it working using the link posted by Chris?

**Comment by githubier** [comment]
Could you tell me how to use it? I modify the example in the wiki to train other net, it show me error

**Comment by javadba** [comment]
Yes it is true that usage notes for examples are mostly lacking.
