### ISSUE TITLE
About the relations of spark.task.cpus and devices?

### ISSUE THREAD

**Issue by chris0927** [yahoo/CaffeOnSpark#201]
I run in GPU mode. Is spark.task.cpus == devices?

**Comment by chris0927** [comment]
When I  test minist in GPU mode, I find that is fastest for using 4 cores and 2 devices

**Comment by junshi15** [comment]
devices is GPU devices, 

spark.task.cpus  is "Number of cores to allocate for each task.", according to this page: http://spark.apache.org/docs/latest/configuration.html

**Comment by chris0927** [comment]
OK,thanks.
