### ISSUE TITLE
Error while building caffe-distri

### ISSUE THREAD

**Issue by LiuChuangyi** [yahoo/CaffeOnSpark#203]
I am trying to get CaffeOnSpark running locally and I have compiled and ran caffe successfully
The whole error stack when I make build is:
hadoop@ubuntu:/usr/local/CaffeOnSpark-master$ make build
cd caffe-public; make proto; make -j4 -e distribute; cd ..
make[1]: Entering directory '/usr/local/CaffeOnSpark-master/caffe-public'
make[1]: Nothing to be done for 'proto'.
make[1]: Leaving directory '/usr/local/CaffeOnSpark-master/caffe-public'
make[1]: Entering directory '/usr/local/CaffeOnSpark-master/caffe-public'
# add proto
cp -r src/caffe/proto distribute/
# add include
cp -r include distribute/
mkdir -p distribute/include/caffe/proto
cp .build_release/src/caffe/proto/caffe.pb.h distribute/include/caffe/proto
# add tool and example binaries
cp .build_release/tools/convert_imageset.bin .build_release/tools/test_net.bin .build_release/tools/train_net.bin .build_release/tools/extract_features.bin .build_release/tools/upgrade_solver_proto_text.bin .build_release/tools/upgrade_net_proto_text.bin .build_release/tools/caffe.bin .build_release/tools/device_query.bin .build_release/tools/finetune_net.bin .build_release/tools/upgrade_net_proto_binary.bin .build_release/tools/net_speed_benchmark.bin .build_release/tools/compute_image_mean.bin distribute/bin
cp .build_release/examples/mnist/convert_mnist_data.bin .build_release/examples/cpp_classification/classification.bin .build_release/examples/cifar10/convert_cifar_data.bin .build_release/examples/siamese/convert_mnist_siamese_data.bin distribute/bin
# add libraries
cp .build_release/lib/libcaffe.a distribute/lib
install -m 644 .build_release/lib/libcaffe.so.1.0.0-rc3 distribute/lib
cd distribute/lib; rm -f libcaffe.so;   ln -s libcaffe.so.1.0.0-rc3 libcaffe.so
# add python - it's not the standard way, indeed...
cp -r python distribute/python
make[1]: Leaving directory '/usr/local/CaffeOnSpark-master/caffe-public'
export LD_LIBRARY_PATH="/usr/local/CaffeOnSpark-master/caffe-public/distribute/lib:/usr/local/CaffeOnSpark-master/caffe-distri/distribute/lib:/usr/local/CaffeOnSpark-master/caffe-public/distribute/lib:/usr/local/CaffeOnSpark-master/caffe-distri/distribute/lib:/usr/lib64:/lib64 "; mvn  -B package -DskipTests
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.yahoo.ml:caffe-grid:jar:0.1-SNAPSHOT
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] caffe
[INFO] caffe-distri
[INFO] caffe-grid
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building caffe 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building caffe-distri 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (proto) @ caffe-distri ---
[INFO] Executing tasks

protoc:
     [exec] make[1]: Entering directory '/usr/local/CaffeOnSpark-master/caffe-distri'
     [exec] PROTOC ../caffe-public/distribute/proto/caffe.proto
     [exec] make[1]: Leaving directory '/usr/local/CaffeOnSpark-master/caffe-distri'
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (compile-generator) @ caffe-distri ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 10 source files to /usr/local/CaffeOnSpark-master/caffe-distri/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ caffe-distri ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /usr/local/CaffeOnSpark-master/caffe-distri/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ caffe-distri ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 10 source files to /usr/local/CaffeOnSpark-master/caffe-distri/target/classes
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (make) @ caffe-distri ---
[INFO] Executing tasks

make:
     [exec] make[1]: Entering directory '/usr/local/CaffeOnSpark-master/caffe-distri'
     [exec] javah -d include/jni -force -cp target/classes \
     [exec] com.yahoo.ml.jcaffe.MatVector
     [exec] javah -d include/jni -force -cp target/classes \
     [exec] com.yahoo.ml.jcaffe.FloatBlob
     [exec] javah -d include/jni -force -cp target/classes \
     [exec] com.yahoo.ml.jcaffe.FloatDataTransformer
     [exec] javah -d include/jni -force -cp target/classes \
     [exec] com.yahoo.ml.jcaffe.CaffeNet
     [exec] javah -d include/jni -force -cp target/classes \
     [exec] com.yahoo.ml.jcaffe.Mat
     [exec] javah -d include/jni -force -cp target/classes \
     [exec] com.yahoo.ml.jcaffe.FloatArray
     [exec] CXX src/main/cpp/CaffeNet.cpp
     [exec] make[1]: *** [.build_release/src/main/cpp/CaffeNet.o] Error 1
     [exec] src/main/cpp/CaffeNet.cpp: In constructor ‘CaffeNet<Dtype>::CaffeNet(const string&, const string&, const string&, int, int, int, bool, int, int)’:
     [exec] src/main/cpp/CaffeNet.cpp:185:55: error: ‘class caffe::MemoryDataParameter’ has no member named ‘set_share_in_parallel’
     [exec]              layer_param->mutable_memory_data_param()->set_share_in_parallel(false);
     [exec]                                                        ^
     [exec] Makefile:413: recipe for target '.build_release/src/main/cpp/CaffeNet.o' failed
     [exec] make[1]: Leaving directory '/usr/local/CaffeOnSpark-master/caffe-distri'
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] caffe .............................................. SUCCESS [  0.018 s]
[INFO] caffe-distri ....................................... FAILURE [ 47.884 s]
[INFO] caffe-grid ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 48.858 s
[INFO] Finished at: 2016-12-06T03:23:02+08:00
[INFO] Final Memory: 15M/92M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (make) on project caffe-distri: An Ant BuildException has occured: exec returned: 2
[ERROR] around Ant part ...<exec failonerror="true" dir="/usr/local/CaffeOnSpark-master/caffe-distri" executable="make">... @ 5:96 in /usr/local/CaffeOnSpark-master/caffe-distri/target/antrun/build-make.xml
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :caffe-distri
Makefile:19: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by junshi15** [comment]
What's your protobuf version? This code only works with 2.5.
