### ISSUE TITLE
CudaSuccess (2 vs. 0)  out of memory when I train in CPU mode,why??

### ISSUE THREAD

**Issue by chris0927** [yahoo/CaffeOnSpark#204]
I use 2 worker  instances,I set CPU mode,but there is this error:

F1206 16:55:19.914152  3830 parallel.cpp:85] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***

**Comment by junshi15** [comment]
If you just want to use CPU, please turn on this flag:
https://github.com/yahoo/caffe/blob/fc0a02efd720bdc29b2f1d93e5354f19a2b9d559/Makefile.config.example#L8

You probably compiled the code with GPU enabled, but run it with CPU-only as specified in solver.prototxt. This should still work, but it will touch GPU. Your error message suggests exactly that: you GPU memory was too small for the job although the job should be run on CPU.

**Comment by chris0927** [comment]
yes,you are right.I have compiled the code with CPU-only enabled.It works well.
