### ISSUE TITLE
compile latest code with sudo make build, but failed with following errors.

### ISSUE THREAD

**Issue by dejunzhang** [yahoo/CaffeOnSpark#22]
[ERROR] /home/atlas/work/caffe_spark/CaffeOnSpark-master/caffe-grid/src/main/scala/com/yahoo/ml/caffe/ImageDataFrame.scala:36: error: value getDataframeColumnSelectCount is not a member of caffe.Caffe.MemoryDataParameter
[INFO]     if (memdatalayer_param.getDataframeColumnSelectCount() > 0) {
[INFO]                            ^
[ERROR] /home/atlas/work/caffe_spark/CaffeOnSpark-master/caffe-grid/src/main/scala/com/yahoo/ml/caffe/ImageDataFrame.scala:37: error: value getDataframeColumnSelectList is not a member of caffe.Caffe.MemoryDataParameter
[INFO]       val selects = memdatalayer_param.getDataframeColumnSelectList()
[INFO]                                        ^
[ERROR] /home/atlas/work/caffe_spark/CaffeOnSpark-master/caffe-grid/src/main/scala/com/yahoo/ml/caffe/ImageDataFrame.scala:58: error: value getImageEncoded is not a member of caffe.Caffe.MemoryDataParameter
[INFO]         val encoded : Boolean = if (!has_encoded) memdatalayer_param.getImageEncoded() else row.getAs[Boolean]("encoded")
[INFO]                                                                      ^
[ERROR] three errors found

**Comment by mriduljain** [comment]
Please update the caffe-public, make clean and rebuild.

**Comment by mriduljain** [comment]
This is likely due to the latest feature addition of Dataframes.

**Comment by anfeng** [comment]
@dejunzhang did it work for you? Since we introduced some changes into BVLC caffe code, you need to 
   (1) make update
   (2) make build

**Comment by dejunzhang** [comment]
@anfeng, Thank you for your reply. I am working on the last version. and i find that @mriduljain was right. i missed update caffe-public. i will have a try later. Thanks again:).

**Comment by rahulbhalerao001** [comment]
After doing a git pull on latest AMI, and doing make update and make build I am getting the following error 
     [exec] Makefile:6: *** ../caffe-public/Makefile.config not found. See ../caffe-public/Makefile.config.example..  Stop.
     [exec] make[1]: Entering directory `/root/CaffeOnSpark/caffe-distri'
     [exec] make[1]: Leaving directory `/root/CaffeOnSpark/caffe-distri'

**Comment by rahulbhalerao001** [comment]
NFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] caffe ............................................. SUCCESS [0.002s]
[INFO] caffe-distri ...................................... FAILURE [1.159s]
[INFO] caffe-grid ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------

**Comment by mriduljain** [comment]
You need to copy the Makefile.config from example file. See the compile steps again

**Comment by dejunzhang** [comment]
@rahulbhalerao001 ,you can have a try like below:
sudo env "PATH=$PATH" make build

**Comment by rahulbhalerao001** [comment]
@mriduljain @dejunzhang  thank you for your help.

I missed the Makefile.config step because I was directly using the AMI.
