### ISSUE TITLE
Changing the caffe version in caffe-public?

### ISSUE THREAD

**Issue by baristahell** [yahoo/CaffeOnSpark#223]
Ok so I'm using a distributed file system and computational power and it now works with simple Caffe, using CaffeOnSpark and some adjustments.
But I now need to train nets for more complex tasks, including object localization.

I already used standalone [MSCNN](https://github.com/zhaoweicai/mscnn) but just wanted to know if replacing caffe-public in caffeonspark by caffe-mscnn (knowing it has some differences in the data layers etc) before compiling was viable.
I tried it, but i get the following issue : 

> protoc:
>     [exec] make[1]: Entering directory `/opt/CaffeOnSpark/caffe-distri'
>     [exec] make[1]: Leaving directory `/opt/CaffeOnSpark/caffe-distri'
>     [exec] make[1]: *** No rule to make target `../caffe-public/distribute/proto/caffe.proto', needed by >`src/main/java/caffe/Caffe.java'.  Stop.

Still, i have the feeling it's not because of the caffe version.
Has anyone tried changing the caffe version to benefit from new layers, etc in CaffeOnSpark?
If so, what are the things you had to do to make sure it worked?
Thanks.

**Comment by junshi15** [comment]
We occasionally update caffe-public to pull in commits from BVLC caffe. A few files, especially the memory data layer, likely need a manual merge. I don't know much about MSCNN. But if it is close enough to BVLC caffe, you may be able to use it in place of caffe-public. 

Your error with protoc does not seem to be related to caffe version. It is more likely your Makefile.config was not set properly. Make sure you modify that file accordingly.

**Comment by baristahell** [comment]
Yeah, sorry, didn't update my post, i found what my issue was and saw what prevented me from compiling a "MscnnOnSpark". It's quite different from BVLC and modifying all the Makefiles etc manually will be tedious.

Well either way, thanks for your answer.
