### ISSUE TITLE
Error with make build for CaffeOnSpark

### ISSUE THREAD

**Issue by malia05** [yahoo/CaffeOnSpark#225]
Hi, can you help me, I installed CaffeOnSpark on my UBUNTU 32 bits, when I make Build on CaffeOnSpark, I have errors as shows below:

cd caffe-public; make proto; make -j4 -e distribute; cd ..
make[1]: entrant dans le répertoire « /home/inf/CaffeOnSpark/caffe-public »
make[1]: Rien à faire pour « proto ».
make[1]: quittant le répertoire « /home/inf/CaffeOnSpark/caffe-public »
make[1]: entrant dans le répertoire « /home/inf/CaffeOnSpark/caffe-public »
CXX src/caffe/data_transformer.cpp
CXX src/caffe/layers/base_conv_layer.cpp
CXX src/caffe/layers/log_layer.cpp
CXX src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp
src/caffe/data_transformer.cpp:2:33: fatal error: opencv2/core/core.hpp: Aucun fichier ou dossier de ce type
 #include <opencv2/core/core.hpp>
                                 ^
compilation terminated.
make[1]: *** [.build_release/src/caffe/data_transformer.o] Erreur 1
make[1]: *** Attente des tâches non terminées....
make[1]: quittant le répertoire « /home/inf/CaffeOnSpark/caffe-public »
export LD_LIBRARY_PATH="/home/y/lib64:/home/y/lib64/mkl/intel64:/usr/local/cuda/:/home/inf/CaffeOnSpark/CaffeOnSpark/caffe-public/distribute/lib:/home/inf/CaffeOnSpark/CaffeOnSpark/caffe-distri/distribute/lib:/usr/lib64:/lib64 "; GLOG_minloglevel=1 mvn  -B package -DskipTests
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.yahoo.ml:caffe-grid:jar:0.1-SNAPSHOT
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] caffe
[INFO] caffe-distri
[INFO] caffe-grid
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building caffe 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building caffe-distri 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (proto) @ caffe-distri ---
[INFO] Executing tasks

protoc:
     [exec] make[1]: entrant dans le répertoire « /home/inf/CaffeOnSpark/caffe-distri »
     [exec] make[1]: quittant le répertoire « /home/inf/CaffeOnSpark/caffe-distri »
     [exec] make[1]: *** Pas de règle pour fabriquer la cible « ../caffe-public/distribute/proto/caffe.proto », nécessaire pour « src/main/java/caffe/Caffe.java ». Arrêt.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] caffe ............................................. SUCCESS [0.002s]
[INFO] caffe-distri ...................................... FAILURE [1.220s]
[INFO] caffe-grid ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.547s
[INFO] Finished at: Sat Jan 21 20:52:06 CET 2017
[INFO] Final Memory: 8M/112M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (proto) on project caffe-distri: An Ant BuildException has occured: exec returned: 2
[ERROR] around Ant part ...<exec failonerror="true" dir="/home/inf/CaffeOnSpark/caffe-distri" executable="make">... @ 5:88 in /home/inf/CaffeOnSpark/caffe-distri/target/antrun/build-protoc.xml
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :caffe-distri
make: *** [build] Erreur 1

Please, can any one help me, I passed 1 month in searching but without find the solution....

**Comment by junshi15** [comment]
The line below shows you are missing opencv2.
src/caffe/data_transformer.cpp:2:33: fatal error: opencv2/core/core.hpp: Aucun fichier ou dossier de ce type

Make sure you install the required packages for BVLC caffe. 
http://caffe.berkeleyvision.org/installation.html

**Comment by malia05** [comment]
Thanks so much junshi15  for your interest answer, I installed libopencv-dev ans the make build on CaffeOnSpark passed successfully.......

**Comment by malia05** [comment]
Thanks so much junshi15 for your interest answer, I installed libopencv-dev ans the make build on CaffeOnSpark passed successfully.......
