### ISSUE TITLE
stuck in command:"hadoop fs -mkdir -p /projects/machine_learning/image_dataset"

### ISSUE THREAD

**Issue by libeiUCAS** [yahoo/CaffeOnSpark#253]
I have installed CaffeOnSpark.when i execute step 7:hadoop fs -mkdir -p   projects/machine_learning/image_dataset (https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_yarn).It    stucks and have no error information . This command can not execute.
I have installed hadoop and spark.there are a master and a slave .they work well.
appreciate your help.

**Comment by junshi15** [comment]
That command creates a directory in your hdfs. Are you able to create a folder in your hdfs? 
Maybe you need the full path, something like
hadoop fs -mkdir -p hdfs://your_name_node:port/path/to/your/new/folder

**Comment by libeiUCAS** [comment]
It is my hadoop config problem. when i reconfig hadoop well ,the question solved.
Still thanks your help.
