### ISSUE TITLE
Parameter synchronization mode

### ISSUE THREAD

**Issue by bjlgcxc** [yahoo/CaffeOnSpark#295]
As I can see, CaffeOnSpark do the synchronization of parameters per iteration. 
 Is there some way to let CaffeOnSpark do that in round, which contains certain number of iterations.For 
example, do the parameter synchronization ervery 10 iterations.(This idea is similar to the mode that SparkNet adopt) 
Looking forward to your reply! 3Q

**Comment by junshi15** [comment]
It is not support directly. To achieve that you have to change the on_start() and on_gradients_ready() function in [this file](https://github.com/yahoo/CaffeOnSpark/blob/master/caffe-distri/src/main/cpp/util/socket_sync.cpp).

**Comment by bjlgcxc** [comment]
ok, thank you very much! I will try it later
