### ISSUE TITLE
Is CaffeOnSpark still being maintained and developed?

### ISSUE THREAD

**Issue by sophia-wright-blue** [yahoo/CaffeOnSpark#300]
Hello,

 I was wondering if CaffeOnSpark is still being maintained and developed - what is the most convenient way to run caffe models with the advantage of Spark RDDs - a cloud platform like Databricks?

Thanks,

**Comment by junshi15** [comment]
CaffeOnSpark is not being developed. It works with an old version of caffe (around 2016). You are encouraged to use [TensorflowOnSpark](https://github.com/yahoo/TensorFlowOnSpark) instead.

**Comment by sophia-wright-blue** [comment]
Will do! thank you for replying.
