### ISSUE TITLE
ERROR: Read partial messageheader

### ISSUE THREAD

**Issue by chengdianxuezi** [yahoo/CaffeOnSpark#33]
I run CaffeOnSpark,but programe sometime can't work out,the ERROR is 

16/03/21 17:28:22 INFO storage.BlockManager: Found block rdd_0_1 locally
E0321 17:28:24.265156  2261 socket.cpp:61] ERROR: Read partial messageheader [8 of 12]
16/03/21 17:29:22 ERROR executor.CoarseGrainedExecutorBackend: RECEIVED SIGNAL 15: SIGTERM
16/03/21 17:29:22 INFO storage.DiskBlockManager: Shutdown hook called
16/03/21 17:29:22 INFO util.ShutdownHookManager: Shutdown hook called

**Comment by chengdianxuezi** [comment]
export LD_LIBRARY_PATH=/home/hadoop/projects/CaffeOnSpark/caffe-public/distribute/lib:/home/hadoop/projects/CaffeOnSpark/caffe-distri/distribute/lib
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-7.5/lib64:/opt/OpenBLAS/lib
export SPARK_WORKER_INSTANCES=2
export DEVICES=1

spark-submit --master yarn --deploy-mode cluster \
    --num-executors 2 \
    --files /home/hadoop/projects/CaffeOnSpark/data/lenet_memory_solver.prototxt,/home/hadoop/projects/CaffeOnSpark/data/lenet_memory_train_test.prototxt \
    --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
    --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
    --class com.yahoo.ml.caffe.CaffeOnSpark  \
    /home/hadoop/projects/CaffeOnSpark/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
        -train \
        -features accuracy,loss -label label \
        -conf lenet_memory_solver.prototxt \
        -devices 5 \
    -connection ethernet \
        -model test1 \
        -output testresult1



if I set devices 2,the program run successfully.But if I set devices 5,It failed

**Comment by junshi15** [comment]
you need set your executor and driver memory properly. see my comment at https://github.com/yahoo/CaffeOnSpark/issues/32

**Comment by chengdianxuezi** [comment]
thank you
