### ISSUE TITLE
how can i get the trainning accuaracy from the log?

### ISSUE THREAD

**Issue by dejunzhang** [yahoo/CaffeOnSpark#46]
Hi, we can run cifar10 full trainning with the below command:
spark-submit --master yarn --deploy-mode cluster     --num-executors 1  \
 --executor-memory 6g --executor-cores 5 \
   --files ./data/cifar10_full_solver.prototxt,./data/cifar10_full_train_test.prototxt,./data/mean.binaryproto   \
   --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}"     --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}"    \
   --class com.yahoo.ml.caffe.CaffeOnSpark      ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar   \
   -train         -features accuracy,loss -label label         -conf cifar10_full_solver.prototxt         -devices 1    -connection ethernet   \
   -model result/cifar10.full.model.h5         -output result/cifar10_full_features_result

And we can also get the below logs from the slave node, but we cann't get training accuracy during the training, is there any command parameters that can be used to print the accuracy information, thank you very much .

I0330 15:37:31.712399 29236 sgd_solver.cpp:106] Iteration 67800, lr = 0.001
16/03/30 15:37:38 INFO executor.Executor: Finished task 0.0 in stage 137.0 (TID 137). 2001 bytes result sent to driver
16/03/30 15:37:38 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 138
16/03/30 15:37:38 INFO executor.Executor: Running task 0.0 in stage 138.0 (TID 138)
16/03/30 15:37:38 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 139
16/03/30 15:37:38 INFO storage.MemoryStore: Block broadcast_139_piece0 stored as bytes in memory (estimated size 1375.0 B, free 32.1 KB)
16/03/30 15:37:38 INFO broadcast.TorrentBroadcast: Reading broadcast variable 139 took 7 ms
16/03/30 15:37:38 INFO storage.MemoryStore: Block broadcast_139 stored as values in memory (estimated size 2.1 KB, free 34.1 KB)
16/03/30 15:37:38 INFO storage.BlockManager: Found block rdd_0_0 locally
I0330 15:37:38.796069 29236 solver.cpp:237] Iteration 68000, loss = 0.362456
I0330 15:37:38.796123 29236 solver.cpp:253]     Train net output #0: loss = 0.362456 (* 1 = 0.362456 loss)
I0330 15:37:38.796150 29236 sgd_solver.cpp:106] Iteration 68000, lr = 0.001
I0330 15:37:45.877544 29236 solver.cpp:237] Iteration 68200, loss = 0.490983
I0330 15:37:45.877589 29236 solver.cpp:253]     Train net output #0: loss = 0.490983 (* 1 = 0.490983 loss)
I0330 15:37:45.877604 29236 sgd_solver.cpp:106] Iteration 68200, lr = 0.001
I0330 15:37:52.965775 29236 solver.cpp:237] Iteration 68400, loss = 0.379639
I0330 15:37:52.965844 29236 solver.cpp:253]     Train net output #0: loss = 0.379639 (* 1 = 0.379639 loss)
I0330 15:37:52.965878 29236 sgd_solver.cpp:106] Iteration 68400, lr = 0.001
16/03/30 15:37:56 INFO executor.Executor: Finished task 0.0 in stage 138.0 (TID 138). 2001 bytes result sent to driver
16/03/30 15:37:56 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 139
16/03/30 15:37:56 INFO executor.Executor: Running task 0.0 in stage 139.0 (TID 139)
16/03/30 15:37:56 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 140
16/03/30 15:37:56 INFO storage.MemoryStore: Block broadcast_140_piece0 stored as bytes in memory (estimated size 1375.0 B, free 35.5 KB)
16/03/30 15:37:56 INFO broadcast.TorrentBroadcast: Reading broadcast variable 140 took 9 ms
16/03/30 15:37:56 INFO storage.MemoryStore: Block broadcast_140 stored as values in memory (estimated size 2.1 KB, free 37.5 KB)
16/03/30 15:37:56 INFO storage.BlockManager: Found block rdd_0_0 locally
I0330 15:38:00.052302 29236 solver.cpp:237] Iteration 68600, loss = 0.358753
I0330 15:38:00.052367 29236 solver.cpp:253]     Train net output #0: loss = 0.358753 (* 1 = 0.358753 loss)
I0330 15:38:00.052400 29236 sgd_solver.cpp:106] Iteration 68600, lr = 0.001
I0330 15:38:07.139724 29236 solver.cpp:237] Iteration 68800, loss = 0.395479
I0330 15:38:07.139791 29236 solver.cpp:253]     Train net output #0: loss = 0.395479 (* 1 = 0.395479 loss)
I0330 15:38:07.139824 29236 sgd_solver.cpp:106] Iteration 68800, lr = 0.001
16/03/30 15:38:13 INFO executor.Executor: Finished task 0.0 in stage 139.0 (TID 139). 2001 bytes result sent to driver
16/03/30 15:38:13 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 140
16/03/30 15:38:13 INFO executor.Executor: Running task 0.0 in stage 140.0 (TID 140)
16/03/30 15:38:13 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 141
16/03/30 15:38:13 INFO storage.MemoryStore: Block broadcast_141_piece0 stored as bytes in memory (estimated size 1375.0 B, free 38.9 KB)
16/03/30 15:38:13 INFO broadcast.TorrentBroadcast: Reading broadcast variable 141 took 9 ms
16/03/30 15:38:13 INFO storage.MemoryStore: Block broadcast_141 stored as values in memory (estimated size 2.1 KB, free 40.9 KB)
16/03/30 15:38:13 INFO storage.BlockManager: Found block rdd_0_0 locally
I0330 15:38:14.222049 29236 solver.cpp:237] Iteration 69000, loss = 0.361772
I0330 15:38:14.222107 29236 solver.cpp:253]     Train net output #0: loss = 0.361772 (* 1 = 0.361772 loss)
I0330 15:38:14.222134 29236 sgd_solver.cpp:106] Iteration 69000, lr = 0.001
I0330 15:38:21.309873 29236 solver.cpp:237] Iteration 69200, loss = 0.48632
I0330 15:38:21.309912 29236 solver.cpp:253]     Train net output #0: loss = 0.48632 (* 1 = 0.48632 loss)
I0330 15:38:21.309931 29236 sgd_solver.cpp:106] Iteration 69200, lr = 0.001
I0330 15:38:28.487985 29236 solver.cpp:237] Iteration 69400, loss = 0.377639
I0330 15:38:28.488052 29236 solver.cpp:253]     Train net output #0: loss = 0.377639 (* 1 = 0.377639 loss)
I0330 15:38:28.488085 29236 sgd_solver.cpp:106] Iteration 69400, lr = 0.001
16/03/30 15:38:31 INFO executor.Executor: Finished task 0.0 in stage 140.0 (TID 140). 2001 bytes result sent to driver
16/03/30 15:38:31 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 141
16/03/30 15:38:31 INFO executor.Executor: Running task 0.0 in stage 141.0 (TID 141)
16/03/30 15:38:31 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 142
16/03/30 15:38:31 INFO storage.MemoryStore: Block broadcast_142_piece0 stored as bytes in memory (estimated size 1375.0 B, free 42.3 KB)
16/03/30 15:38:31 INFO broadcast.TorrentBroadcast: Reading broadcast variable 142 took 7 ms
16/03/30 15:38:31 INFO storage.MemoryStore: Block broadcast_142 stored as values in memory (estimated size 2.1 KB, free 44.3 KB)
16/03/30 15:38:31 INFO storage.BlockManager: Found block rdd_0_0 locally
I0330 15:38:35.572760 29236 solver.cpp:237] Iteration 69600, loss = 0.35981
I0330 15:38:35.572826 29236 solver.cpp:253]     Train net output #0: loss = 0.35981 (* 1 = 0.35981 loss)
I0330 15:38:35.572860 29236 sgd_solver.cpp:106] Iteration 69600, lr = 0.001
I0330 15:38:42.656687 29236 solver.cpp:237] Iteration 69800, loss = 0.390506
I0330 15:38:42.656752 29236 solver.cpp:253]     Train net output #0: loss = 0.390506 (* 1 = 0.390506 loss)
I0330 15:38:42.656810 29236 sgd_solver.cpp:106] Iteration 69800, lr = 0.001
16/03/30 15:38:49 INFO executor.Executor: Finished task 0.0 in stage 141.0 (TID 141). 2001 bytes result sent to driver
16/03/30 15:38:49 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 142
16/03/30 15:38:49 INFO executor.Executor: Running task 0.0 in stage 142.0 (TID 142)
16/03/30 15:38:49 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 143
16/03/30 15:38:49 INFO storage.MemoryStore: Block broadcast_143_piece0 stored as bytes in memory (estimated size 1375.0 B, free 45.7 KB)
16/03/30 15:38:49 INFO broadcast.TorrentBroadcast: Reading broadcast variable 143 took 9 ms
16/03/30 15:38:49 INFO storage.MemoryStore: Block broadcast_143 stored as values in memory (estimated size 2.1 KB, free 47.7 KB)
16/03/30 15:38:49 INFO storage.BlockManager: Found block rdd_0_0 locally
16/03/30 15:38:49 INFO caffe.CaffeProcessor: Model saving into file at the end of training:result/cifar10.full.model.h5
I0330 15:38:49.704614 29236 solver.cpp:469] Snapshotting to HDF5 file cifar10_full_iter_70000.caffemodel.h5
I0330 15:38:49.733238 29236 sgd_solver.cpp:283] Snapshotting solver state to HDF5 file cifar10_full_iter_70000.solverstate.h5
16/03/30 15:38:49 INFO caffe.FSUtils$: destination file:result/cifar10.full.model.h5
16/03/30 15:38:49 INFO executor.Executor: Finished task 0.0 in stage 142.0 (TID 142). 2001 bytes result sent to driver
16/03/30 15:38:49 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 143
16/03/30 15:38:49 INFO executor.Executor: Running task 0.0 in stage 143.0 (TID 143)
16/03/30 15:38:49 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 144
16/03/30 15:38:49 INFO storage.MemoryStore: Block broadcast_144_piece0 stored as bytes in memory (estimated size 1259.0 B, free 49.0 KB)
16/03/30 15:38:49 INFO broadcast.TorrentBroadcast: Reading broadcast variable 144 took 7 ms
16/03/30 15:38:49 INFO storage.MemoryStore: Block broadcast_144 stored as values in memory (estimated size 2016.0 B, free 50.9 KB)
16/03/30 15:38:49 INFO executor.Executor: Finished task 0.0 in stage 143.0 (TID 143). 899 bytes result sent to driver
16/03/30 15:38:50 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 144
16/03/30 15:38:50 INFO executor.Executor: Running task 0.0 in stage 144.0 (TID 144)
16/03/30 15:38:50 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 145
16/03/30 15:38:50 INFO storage.MemoryStore: Block broadcast_145_piece0 stored as bytes in memory (estimated size 1973.0 B, free 52.9 KB)
16/03/30 15:38:50 INFO broadcast.TorrentBroadcast: Reading broadcast variable 145 took 9 ms
16/03/30 15:38:50 INFO storage.MemoryStore: Block broadcast_145 stored as values in memory (estimated size 2.9 KB, free 55.8 KB)
16/03/30 15:38:50 INFO caffe.CaffeProcessor: my rank is 0
16/03/30 15:38:50 INFO caffe.LMDB: Batch size:100
I0330 15:38:50.147389 29220 CaffeNet.cpp:78] set root solver device id to 0
I0330 15:38:50.148255 29220 solver.cpp:48] Initializing solver from parameters: 
test_iter: 100
test_interval: 70001
base_lr: 0.001
display: 200
max_iter: 70000
lr_policy: "fixed"
momentum: 0.9
weight_decay: 0.004
stepsize: 30000
snapshot: 70001
snapshot_prefix: "cifar10_full"
solver_mode: GPU
device_id: 0
net_param {
  name: "CIFAR10_full"
  layer {
    name: "cifar"
    type: "MemoryData"
    top: "data"
    top: "label"
    include {
      phase: TRAIN
    }
    memory_data_param {
      batch_size: 100
      channels: 3
      height: 32
      width: 32
      share_in_parallel: false
      source: "file:///home/atlas/work/caffe_spark/CaffeOnSpark-master/data/cifar10_train_lmdb/"
    }
    source_class: "com.yahoo.ml.caffe.LMDB"
  }
 //....................---delete some logs......
I0330 15:38:50.185540 29220 net.cpp:228] label_cifar_1_split does not need backward computation.
I0330 15:38:50.185547 29220 net.cpp:228] cifar does not need backward computation.
I0330 15:38:50.185554 29220 net.cpp:270] This network produces output accuracy
I0330 15:38:50.185561 29220 net.cpp:270] This network produces output loss
I0330 15:38:50.185586 29220 net.cpp:283] Network initialization done.
I0330 15:38:50.185653 29220 solver.cpp:60] Solver scaffolding done.
I0330 15:38:50.186189 29220 CaffeNet.cpp:248] Finetuning from /tmp/hadoop-atlas/nm-local-dir/usercache/atlas/appcache/application_1459254969589_0006/container_1459254969589_0006_01_000002/model.tmp.h5
I0330 15:38:50.186841 29220 hdf5.cpp:32] Datatype class: H5T_FLOAT
I0330 15:38:50.189332 29220 parallel.cpp:392] GPUs pairs 
16/03/30 15:38:50 INFO executor.Executor: Finished task 0.0 in stage 144.0 (TID 144). 870 bytes result sent to driver
16/03/30 15:38:50 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 145
16/03/30 15:38:50 INFO executor.Executor: Running task 0.0 in stage 145.0 (TID 145)
16/03/30 15:38:50 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 146
16/03/30 15:38:50 INFO storage.MemoryStore: Block broadcast_146_piece0 stored as bytes in memory (estimated size 6.5 KB, free 62.2 KB)
16/03/30 15:38:50 INFO broadcast.TorrentBroadcast: Reading broadcast variable 146 took 9 ms
16/03/30 15:38:50 INFO storage.MemoryStore: Block broadcast_146 stored as values in memory (estimated size 14.1 KB, free 76.3 KB)
16/03/30 15:38:51 INFO spark.CacheManager: Partition rdd_154_0 not found, computing it
16/03/30 15:38:51 INFO spark.CacheManager: Partition rdd_148_0 not found, computing it
16/03/30 15:38:51 INFO caffe.LmdbRDD: Processing partition 0
16/03/30 15:38:52 INFO caffe.LmdbRDD: Completed partition 0
16/03/30 15:38:52 INFO storage.BlockManager: Found block rdd_148_0 locally
I0330 15:38:52.011971   954 MemoryInputAdapter.cpp:15] MemoryInputAdapter is used
I0330 15:38:52.013013   955 data_transformer.cpp:25] Loading mean file from: mean.binaryproto
16/03/30 15:38:52 INFO caffe.LMDB: Completed all files
16/03/30 15:38:53 INFO codegen.GenerateUnsafeProjection: Code generated in 115.18413 ms
16/03/30 15:38:53 INFO storage.BlockManager: Found block rdd_154_0 locally
16/03/30 15:38:53 INFO codegen.GeneratePredicate: Code generated in 3.347353 ms
16/03/30 15:38:53 INFO columnar.GenerateColumnAccessor: Code generated in 16.381273 ms
16/03/30 15:38:53 INFO codegen.GenerateMutableProjection: Code generated in 8.126173 ms
16/03/30 15:38:53 INFO codegen.GenerateUnsafeProjection: Code generated in 6.682903 ms
16/03/30 15:38:53 INFO codegen.GenerateMutableProjection: Code generated in 6.995862 ms
16/03/30 15:38:53 INFO codegen.GenerateUnsafeRowJoiner: Code generated in 5.680261 ms
16/03/30 15:38:53 INFO codegen.GenerateUnsafeProjection: Code generated in 5.733341 ms
16/03/30 15:38:53 INFO executor.Executor: Finished task 0.0 in stage 145.0 (TID 145). 2548 bytes result sent to driver
16/03/30 15:38:53 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 146
16/03/30 15:38:53 INFO executor.Executor: Running task 0.0 in stage 146.0 (TID 146)
16/03/30 15:38:53 INFO spark.MapOutputTrackerWorker: Updating epoch to 1 and clearing cache
16/03/30 15:38:53 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 147
16/03/30 15:38:53 INFO storage.MemoryStore: Block broadcast_147_piece0 stored as bytes in memory (estimated size 4.6 KB, free 80.9 KB)
16/03/30 15:38:53 INFO broadcast.TorrentBroadcast: Reading broadcast variable 147 took 7 ms
16/03/30 15:38:53 INFO storage.MemoryStore: Block broadcast_147 stored as values in memory (estimated size 9.3 KB, free 90.2 KB)
16/03/30 15:38:53 INFO spark.MapOutputTrackerWorker: Don't have map outputs for shuffle 0, fetching them
16/03/30 15:38:53 INFO spark.MapOutputTrackerWorker: Doing the fetch; tracker endpoint = NettyRpcEndpointRef(spark://MapOutputTracker@10.110.52.32:38988)
16/03/30 15:38:53 INFO spark.MapOutputTrackerWorker: Got the output locations
16/03/30 15:38:53 INFO storage.ShuffleBlockFetcherIterator: Getting 1 non-empty blocks out of 1 blocks
16/03/30 15:38:53 INFO storage.ShuffleBlockFetcherIterator: Started 0 remote fetches in 4 ms
16/03/30 15:38:53 INFO codegen.GenerateMutableProjection: Code generated in 7.146091 ms
16/03/30 15:38:53 INFO codegen.GenerateMutableProjection: Code generated in 5.766725 ms
16/03/30 15:38:53 INFO executor.Executor: Finished task 0.0 in stage 146.0 (TID 146). 1663 bytes result sent to driver
16/03/30 15:38:53 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 147
16/03/30 15:38:53 INFO executor.Executor: Running task 0.0 in stage 147.0 (TID 147)
16/03/30 15:38:53 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 148
16/03/30 15:38:53 INFO storage.MemoryStore: Block broadcast_148_piece0 stored as bytes in memory (estimated size 1259.0 B, free 91.4 KB)
16/03/30 15:38:53 INFO broadcast.TorrentBroadcast: Reading broadcast variable 148 took 8 ms
16/03/30 15:38:53 INFO storage.MemoryStore: Block broadcast_148 stored as values in memory (estimated size 2016.0 B, free 93.4 KB)
16/03/30 15:38:53 INFO executor.Executor: Finished task 0.0 in stage 147.0 (TID 147). 899 bytes result sent to driver
16/03/30 15:38:54 INFO executor.CoarseGrainedExecutorBackend: Driver commanded a shutdown
16/03/30 15:38:54 INFO storage.MemoryStore: MemoryStore cleared
16/03/30 15:38:54 INFO storage.BlockManager: BlockManager stopped
16/03/30 15:38:54 WARN executor.CoarseGrainedExecutorBackend: An unknown (yuntu2:38988) driver disconnected.
16/03/30 15:38:54 ERROR executor.CoarseGrainedExecutorBackend: Driver 10.110.52.32:38988 disassociated! Shutting down.
16/03/30 15:38:54 INFO util.ShutdownHookManager: Shutdown hook called
16/03/30 15:38:54 INFO remote.RemoteActorRefProvider$RemotingTerminator: Shutting down remote daemon.
16/03/30 15:38:54 INFO remote.RemoteActorRefProvider$RemotingTerminator: Remote daemon shut down; proceeding with flushing remote transports.
16/03/30 15:38:54 INFO remote.RemoteActorRefProvider$RemotingTerminator: Remoting shut down.

**Comment by mriduljain** [comment]
what do you see here:
hadoop fs -cat result/cifar10_full_features_result

**Comment by anfeng** [comment]
If you just want the overall accuracy, please replace
 "-features accuracy,loss -label label " 
by "-test "

**Comment by dejunzhang** [comment]
@mriduljain i can see:
cat: `result/cifar10_full_features_result': Is a directory
And i can see 3 files in it:
_SUCCESS
part-r-00000-27a44445-1537-4a3e-a087-802e97a35bbc
part-r-00001-27a44445-1537-4a3e-a087-802e97a35bbc

@anfeng, i will have a try, thank you.

**Comment by dejunzhang** [comment]
@mriduljain,@anfeng, now i can get loss and accuracy results, thank you :)
