### ISSUE TITLE
Remote RPC client disassociated

### ISSUE THREAD

**Issue by mauricio-onoda** [yahoo/CaffeOnSpark#48]
We executed MNIST Autoencoder from Caffe example in two different Spark cluster with 2 slaves:  g2.2xlarge (1 GPU, 8 vCPUs) and g2.8xlarge (4 GPUs, 32 vCPUs). We had already modified prototxt files to use MemoryData.
Running the following CLI in both clusters,

-------
spark-submit --master spark://$(hostname):7077 \
    --files mnist_memory_autoencoder_solver.prototxt,mnist_memory_autoencoder.prototxt \
    --conf spark.cores.max=${TOTAL_CORES} \
    --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
    --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
    --class com.yahoo.ml.caffe.CaffeOnSpark  \
    ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
    -train -persistent \
    -features accuracy,loss -label label \
    -conf mnist_memory_autoencoder_solver.prototxt \
    -clusterSize ${SPARK_WORKER_INSTANCES} \
    -devices ${DEVICES} \
    -connection ethernet \
    -model /mnist_memory.model \
    -output /mnist_model_autoencoder

--------

we got an error

```
16/03/31 13:57:36 INFO TaskSetManager: Starting task 1.3 in stage 0.0 (TID 6, ip-172-31-6-221.eu-west-1.compute.internal, partition 1,PROCESS_LOCAL, 2216 bytes)
16/03/31 13:57:36 INFO TaskSetManager: Starting task 0.3 in stage 0.0 (TID 7, ip-172-31-6-221.eu-west-1.compute.internal, partition 0,PROCESS_LOCAL, 2216 bytes)
16/03/31 13:57:37 INFO BlockManagerMasterEndpoint: Registering block manager ip-172-31-6-221.eu-west-1.compute.internal:35232 with 37.9 GB RAM, BlockManagerId(4, ip-172-31-6-221.eu-west-1.compute.internal, 35232)
16/03/31 13:57:37 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on ip-172-31-6-221.eu-west-1.compute.internal:35232 (size: 2.0 KB, free: 37.9 GB)
16/03/31 13:57:39 ERROR TaskSchedulerImpl: Lost executor 4 on ip-172-31-6-221.eu-west-1.compute.internal: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/03/31 13:57:39 WARN TaskSetManager: Lost task 0.3 in stage 0.0 (TID 7, ip-172-31-6-221.eu-west-1.compute.internal): ExecutorLostFailure (executor 4 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/03/31 13:57:39 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
16/03/31 13:57:39 WARN TaskSetManager: Lost task 1.3 in stage 0.0 (TID 6, ip-172-31-6-221.eu-west-1.compute.internal): ExecutorLostFailure (executor 4 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/03/31 13:57:39 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
16/03/31 13:57:39 INFO TaskSchedulerImpl: Cancelling stage 0
16/03/31 13:57:39 INFO DAGScheduler: ResultStage 0 (collect at CaffeOnSpark.scala:125) failed in 11.747 s
16/03/31 13:57:39 INFO DAGScheduler: Job 0 failed: collect at CaffeOnSpark.scala:125, took 11.988590 s
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 7, ip-172-31-6-221.eu-west-1.compute.internal): ExecutorLostFailure (executor 4 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
```

Additionally, we ran successfully this same example (with type "Data" instead ˜MemoryData") in a single notebook.

Could you help us?

Thanks!

**Comment by anfeng** [comment]
I suspect that your batch size is too big. Your batch size should be the original batch size / (devices * executors). See CaffeOnSpark README.

Andy Feng

**Comment by junshi15** [comment]
Please provide executor log.

Spark generates a multitude of logs, divided by containers, the executor log being the most useful one. What you provided is driver log, usually not useful at all. For example, let's say the job failed because an executor ran out of memory, you would get the following (roughly):

executor log: I was given 10Gb memory, but I need to use 12GB, ran out of memory, exiting...
driver log: I can not talk to one of the executors any more, it has quitted? Oh, no, remote RPC connection to that guy is lost, stage failure, blah blah blah...

Hopefully, you can see why the driver log is less useful now.

**Comment by mauricio-onoda** [comment]
We saw our worker logs:

`16/04/01 12:34:12 INFO Worker: Asked to kill executor app-20160401123228-0015/4
16/04/01 12:34:12 INFO ExecutorRunner: Runner thread for executor app-20160401123228-0015/4 interrupted
16/04/01 12:34:12 INFO ExecutorRunner: Killing process!
16/04/01 12:34:12 ERROR FileAppender: Error writing stream to file /root/spark/work/app-20160401123228-0015/4/stderr
java.io.IOException: Stream closed`

It seems this error is know: "SPARK-9844 - File appender race condition during SparkWorker shutdown". We are running Spark 1.6.0. According to the link https://issues.apache.org/jira/browse/SPARK-9844, this problem was fixed in new version 1.6.1. We will install this new version and will test again.

Thanks.

**Comment by mauricio-onoda** [comment]
In our process to create a GPU cluster from Yahoo AMI image with Spark 1.6.1, we changed the following script to load this actual version instead 1.6.0:

`export AMI_IMAGE=ami-6373ca10
...

./spark-ec2 --key-pair=${EC2_KEY} --identity-file=${EC2_PEM_FILE} \
                --region=${EC2_REGION} --zone=${EC2_ZONE} \
                --ebs-vol-size=50 \
                --instance-type=${EC2_INSTANCE_TYPE} \
                --master-instance-type=m4.xlarge \
                --ami=${AMI_IMAGE}  -s ${SPARK_WORKER_INSTANCES} \
                --copy-aws-credentials \
                --hadoop-major-version=yarn --spark-version 1.6.1 \
                --no-ganglia \
                --user-data ${CAFFE_ON_SPARK}/scripts/ec2-cloud-config.txt launch CaffeOnSparkDemo`

Testing this configuration, we got an error:
`Error: Could not find or load main class org.apache.spark.launcher.Main`

How can we fix this problem to execute this new Spark version (1.6.1) with CaffeOnSpark? 
Maybe the right question is: how can we install/run CaffeOnSpark with Spark 1.6.1?

**Comment by junshi15** [comment]
I have not done this myself, but I assume you need to install Spark-1.6.1 first, then use the script from the  new installation.

**Comment by gaohannk** [comment]
Same error file appender problem. Try spark 1.6.1 not solve problem.
