### ISSUE TITLE
 failure in make build complaining about  undefined symbol to python

### ISSUE THREAD

**Issue by nhe150** [yahoo/CaffeOnSpark#5]
[exec] /usr/bin/ld: .build_release/src/main/cpp/tools/caffe_mini_cluster.o: undefined reference to symbol '_ZN5boost6python17error_already_setD1Ev'
     [exec] //usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.54.0: error adding symbols: DSO missing from command line
     [exec] collect2: error: ld returned 1 exit status
     [exec] make[1]: *** [.build_release/src/main/cpp/tools/caffe_mini_cluster.bin] Error 1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] caffe ............................................. SUCCESS [0.003s]
[INFO] caffe-distri ...................................... FAILURE [47.767s]
[INFO] caffe-grid

**Comment by junshi15** [comment]
Can you check your boost version? BVLC caffe requires boost >= 1.55, 
http://caffe.berkeleyvision.org/installation.html, 
We have been using boost 1.57 for the entire CaffeOnSpark compilation.

**Comment by nhe150** [comment]
Thank you. Upgrading to boost 1.57 now.

**Comment by nhe150** [comment]
[exec] CXX src/main/cpp/tools/caffe_mini_cluster.cpp
     [exec] /usr/bin/ld: .build_release/src/main/cpp/tools/caffe_mini_cluster.o: undefined reference to symbol '_ZN5boost6python17error_already_setD1Ev'
     [exec] //usr/lib/x86_64-linux-gnu/libboost_python.so.1.57.0: error adding symbols: DSO missing from command line
     [exec] collect2: error: ld returned 1 exit status
     [exec] make[1]: *** [.build_release/src/main/cpp/tools/caffe_mini_cluster.bin] Error 1
     [exec] CXX/LD -o .build_release/src/main/cpp/tools/caffe_mini_cluster.bin
     [exec] make[1]: Leaving directory `/home/bda-master/nhe/CaffeOnSpark/caffe-distri'

**Comment by nhe150** [comment]
After upgrade to boost 1.57 similiar error happened.

**Comment by mriduljain** [comment]
Looks like this comes in due to the option WITH_PYTHON_LAYER in caffe-public/Makefile.config.
You can either:
1. Comment out this option in caffe-public/Makefile.config
2. If you really need it then you can install boost_python and in caffe-distri/Makefile specify LIBRARIES += boost_python. We will either remove this dependency from caffe_mini_cluster or link to boost_python (will file this as a request)

**Comment by junshi15** [comment]
It looks like a library setting issue. Since we don't use src/main/cpp/tools/caffe_mini_cluster.cpp for spark operation (it is for debugging only), you can just delete it for now and see if the compilation passes.

**Comment by melody-rain** [comment]
I got the same error with libboost_python-py27.so.1.55.0...

**Comment by mriduljain** [comment]
I will send a patch for this soon. Till then you can follow whatever Jun or I comment earlier in this thread.

**Comment by mriduljain** [comment]
This should be solved by the latest merge. Closing it for now. Please reopen if you continue to have problems.

**Comment by nhe150** [comment]
rm src/main/cpp/tools/caffe_mini_cluster.cpp worked
