### ISSUE TITLE
got error java.lang.NullPointerException

### ISSUE THREAD

**Issue by zokri** [yahoo/CaffeOnSpark#54]
can someone help me out with this,
i'v created my own caffemodel, with 20,000 images:

my Train lmdb:
root@ip-172-31-15-194:~/CaffeOnSpark/data/faces# ls -l --block-size=M TrainLmdb/total 2642M
-rwxrwxrwx 1 root root 2642M Apr  4 23:51 data.mdb
-rwxrwxrwx 1 root root    1M Apr  6 11:20 lock.mdb

my Val lmdb:
root@ip-172-31-15-194:~/CaffeOnSpark/data/faces# ls -l --block-size=M ValLmdb/
total 1132M
-rwxrwxrwx 1 root root 1132M Apr  4 23:53 data.mdb
-rwxrwxrwx 1 root root    1M Apr  4 23:53 lock.mdb

2 slaves=> g2.2xlarge
1 master=>m4.xlarge

I0406 11:09:55.750506  3134 layer_factory.hpp:77] Creating layer data
I0406 11:09:55.750524  3134 net.cpp:106] Creating Layer data
I0406 11:09:55.750530  3134 net.cpp:411] data -> data
I0406 11:09:55.750538  3134 net.cpp:411] data -> label
I0406 11:09:55.751267  3134 net.cpp:150] Setting up data
I0406 11:09:55.751286  3134 net.cpp:157] Top shape: 100 3 32 32 (307200)
I0406 11:09:55.751291  3134 net.cpp:157] Top shape: 100 (100)
I0406 11:09:55.751296  3134 net.cpp:165] Memory required for data: 1229200
I0406 11:09:55.751299  3134 layer_factory.hpp:77] Creating layer label_data_1_split
I0406 11:09:55.751312  3134 net.cpp:106] Creating Layer label_data_1_split
I0406 11:09:55.751322  3134 net.cpp:454] label_data_1_split <- label
I0406 11:09:55.751328  3134 net.cpp:411] label_data_1_split -> label_data_1_split_0
I0406 11:09:55.751337  3134 net.cpp:411] label_data_1_split -> label_data_1_split_1
I0406 11:09:55.751381  3134 net.cpp:150] Setting up label_data_1_split
I0406 11:09:55.751396  3134 net.cpp:157] Top shape: 100 (100)
I0406 11:09:55.751401  3134 net.cpp:157] Top shape: 100 (100)
I0406 11:09:55.751405  3134 net.cpp:165] Memory required for data: 1230000
I0406 11:09:55.751410  3134 layer_factory.hpp:77] Creating layer conv1
I0406 11:09:55.751418  3134 net.cpp:106] Creating Layer conv1
I0406 11:09:55.751422  3134 net.cpp:454] conv1 <- data
I0406 11:09:55.751431  3134 net.cpp:411] conv1 -> conv1
I0406 11:09:55.752434  3134 net.cpp:150] Setting up conv1
I0406 11:09:55.752456  3134 net.cpp:157] Top shape: 100 32 32 32 (3276800)
I0406 11:09:55.752461  3134 net.cpp:165] Memory required for data: 14337200
I0406 11:09:55.752471  3134 layer_factory.hpp:77] Creating layer pool1
I0406 11:09:55.752480  3134 net.cpp:106] Creating Layer pool1
I0406 11:09:55.752485  3134 net.cpp:454] pool1 <- conv1
I0406 11:09:55.752490  3134 net.cpp:411] pool1 -> pool1
I0406 11:09:55.752538  3134 net.cpp:150] Setting up pool1
I0406 11:09:55.752553  3134 net.cpp:157] Top shape: 100 32 16 16 (819200)
I0406 11:09:55.752557  3134 net.cpp:165] Memory required for data: 17614000
I0406 11:09:55.752562  3134 layer_factory.hpp:77] Creating layer relu1
I0406 11:09:55.752568  3134 net.cpp:106] Creating Layer relu1
I0406 11:09:55.752573  3134 net.cpp:454] relu1 <- pool1
I0406 11:09:55.752583  3134 net.cpp:397] relu1 -> pool1 (in-place)
I0406 11:09:55.752825  3134 net.cpp:150] Setting up relu1
I0406 11:09:55.752842  3134 net.cpp:157] Top shape: 100 32 16 16 (819200)
I0406 11:09:55.752846  3134 net.cpp:165] Memory required for data: 20890800
I0406 11:09:55.752851  3134 layer_factory.hpp:77] Creating layer conv2
I0406 11:09:55.752861  3134 net.cpp:106] Creating Layer conv2
I0406 11:09:55.752871  3134 net.cpp:454] conv2 <- pool1
I0406 11:09:55.752882  3134 net.cpp:411] conv2 -> conv2
I0406 11:09:55.754490  3134 net.cpp:150] Setting up conv2
I0406 11:09:55.754510  3134 net.cpp:157] Top shape: 100 32 16 16 (819200)
I0406 11:09:55.754514  3134 net.cpp:165] Memory required for data: 24167600
I0406 11:09:55.754524  3134 layer_factory.hpp:77] Creating layer relu2
I0406 11:09:55.754534  3134 net.cpp:106] Creating Layer relu2
I0406 11:09:55.754539  3134 net.cpp:454] relu2 <- conv2
I0406 11:09:55.754547  3134 net.cpp:397] relu2 -> conv2 (in-place)
I0406 11:09:55.754779  3134 net.cpp:150] Setting up relu2
I0406 11:09:55.754797  3134 net.cpp:157] Top shape: 100 32 16 16 (819200)
I0406 11:09:55.754802  3134 net.cpp:165] Memory required for data: 27444400
I0406 11:09:55.754806  3134 layer_factory.hpp:77] Creating layer pool2
I0406 11:09:55.754815  3134 net.cpp:106] Creating Layer pool2
I0406 11:09:55.754828  3134 net.cpp:454] pool2 <- conv2
I0406 11:09:55.754837  3134 net.cpp:411] pool2 -> pool2
I0406 11:09:55.755035  3134 net.cpp:150] Setting up pool2
I0406 11:09:55.755053  3134 net.cpp:157] Top shape: 100 32 8 8 (204800)
I0406 11:09:55.755056  3134 net.cpp:165] Memory required for data: 28263600
I0406 11:09:55.755060  3134 layer_factory.hpp:77] Creating layer conv3
I0406 11:09:55.755074  3134 net.cpp:106] Creating Layer conv3
I0406 11:09:55.755084  3134 net.cpp:454] conv3 <- pool2
I0406 11:09:55.755095  3134 net.cpp:411] conv3 -> conv3
I0406 11:09:55.757617  3134 net.cpp:150] Setting up conv3
I0406 11:09:55.757640  3134 net.cpp:157] Top shape: 100 64 8 8 (409600)
I0406 11:09:55.757644  3134 net.cpp:165] Memory required for data: 29902000
I0406 11:09:55.757654  3134 layer_factory.hpp:77] Creating layer relu3
I0406 11:09:55.757663  3134 net.cpp:106] Creating Layer relu3
I0406 11:09:55.757666  3134 net.cpp:454] relu3 <- conv3
I0406 11:09:55.757671  3134 net.cpp:397] relu3 -> conv3 (in-place)
I0406 11:09:55.757904  3134 net.cpp:150] Setting up relu3
I0406 11:09:55.757921  3134 net.cpp:157] Top shape: 100 64 8 8 (409600)
I0406 11:09:55.757925  3134 net.cpp:165] Memory required for data: 31540400
I0406 11:09:55.757930  3134 layer_factory.hpp:77] Creating layer pool3
I0406 11:09:55.757936  3134 net.cpp:106] Creating Layer pool3
I0406 11:09:55.757941  3134 net.cpp:454] pool3 <- conv3
I0406 11:09:55.757951  3134 net.cpp:411] pool3 -> pool3
I0406 11:09:55.758177  3134 net.cpp:150] Setting up pool3
I0406 11:09:55.758194  3134 net.cpp:157] Top shape: 100 64 4 4 (102400)
I0406 11:09:55.758198  3134 net.cpp:165] Memory required for data: 31950000
I0406 11:09:55.758203  3134 layer_factory.hpp:77] Creating layer ip1
I0406 11:09:55.758209  3134 net.cpp:106] Creating Layer ip1
I0406 11:09:55.758213  3134 net.cpp:454] ip1 <- pool3
I0406 11:09:55.758221  3134 net.cpp:411] ip1 -> ip1
I0406 11:09:55.760910  3134 net.cpp:150] Setting up ip1
I0406 11:09:55.760928  3134 net.cpp:157] Top shape: 100 64 (6400)
I0406 11:09:55.760933  3134 net.cpp:165] Memory required for data: 31975600
I0406 11:09:55.760941  3134 layer_factory.hpp:77] Creating layer ip2
I0406 11:09:55.760951  3134 net.cpp:106] Creating Layer ip2
I0406 11:09:55.760957  3134 net.cpp:454] ip2 <- ip1
I0406 11:09:55.760967  3134 net.cpp:411] ip2 -> ip2
I0406 11:09:55.761073  3134 net.cpp:150] Setting up ip2
I0406 11:09:55.761090  3134 net.cpp:157] Top shape: 100 2 (200)
I0406 11:09:55.761093  3134 net.cpp:165] Memory required for data: 31976400
I0406 11:09:55.761102  3134 layer_factory.hpp:77] Creating layer ip2_ip2_0_split
I0406 11:09:55.761111  3134 net.cpp:106] Creating Layer ip2_ip2_0_split
I0406 11:09:55.761113  3134 net.cpp:454] ip2_ip2_0_split <- ip2
I0406 11:09:55.761119  3134 net.cpp:411] ip2_ip2_0_split -> ip2_ip2_0_split_0
I0406 11:09:55.761126  3134 net.cpp:411] ip2_ip2_0_split -> ip2_ip2_0_split_1
I0406 11:09:55.761178  3134 net.cpp:150] Setting up ip2_ip2_0_split
I0406 11:09:55.761191  3134 net.cpp:157] Top shape: 100 2 (200)
I0406 11:09:55.761196  3134 net.cpp:157] Top shape: 100 2 (200)
I0406 11:09:55.761199  3134 net.cpp:165] Memory required for data: 31978000
I0406 11:09:55.761204  3134 layer_factory.hpp:77] Creating layer accuracy
I0406 11:09:55.761212  3134 net.cpp:106] Creating Layer accuracy
I0406 11:09:55.761221  3134 net.cpp:454] accuracy <- ip2_ip2_0_split_0
I0406 11:09:55.761231  3134 net.cpp:454] accuracy <- label_data_1_split_0
I0406 11:09:55.761240  3134 net.cpp:411] accuracy -> accuracy
I0406 11:09:55.761253  3134 net.cpp:150] Setting up accuracy
I0406 11:09:55.761260  3134 net.cpp:157] Top shape: (1)
I0406 11:09:55.761262  3134 net.cpp:165] Memory required for data: 31978004
I0406 11:09:55.761266  3134 layer_factory.hpp:77] Creating layer loss
I0406 11:09:55.761273  3134 net.cpp:106] Creating Layer loss
I0406 11:09:55.761277  3134 net.cpp:454] loss <- ip2_ip2_0_split_1
I0406 11:09:55.761281  3134 net.cpp:454] loss <- label_data_1_split_1
I0406 11:09:55.761287  3134 net.cpp:411] loss -> loss
I0406 11:09:55.761294  3134 layer_factory.hpp:77] Creating layer loss
I0406 11:09:55.761638  3134 net.cpp:150] Setting up loss
I0406 11:09:55.761658  3134 net.cpp:157] Top shape: (1)
I0406 11:09:55.761662  3134 net.cpp:160]     with loss weight 1
I0406 11:09:55.761670  3134 net.cpp:165] Memory required for data: 31978008
I0406 11:09:55.761674  3134 net.cpp:226] loss needs backward computation.
I0406 11:09:55.761678  3134 net.cpp:228] accuracy does not need backward computation.
I0406 11:09:55.761682  3134 net.cpp:226] ip2_ip2_0_split needs backward computation.
I0406 11:09:55.761685  3134 net.cpp:226] ip2 needs backward computation.
I0406 11:09:55.761689  3134 net.cpp:226] ip1 needs backward computation.
I0406 11:09:55.761693  3134 net.cpp:226] pool3 needs backward computation.
I0406 11:09:55.761695  3134 net.cpp:226] relu3 needs backward computation.
I0406 11:09:55.761698  3134 net.cpp:226] conv3 needs backward computation.
I0406 11:09:55.761703  3134 net.cpp:226] pool2 needs backward computation.
I0406 11:09:55.761705  3134 net.cpp:226] relu2 needs backward computation.
I0406 11:09:55.761708  3134 net.cpp:226] conv2 needs backward computation.
I0406 11:09:55.761711  3134 net.cpp:226] relu1 needs backward computation.
I0406 11:09:55.761714  3134 net.cpp:226] pool1 needs backward computation.
I0406 11:09:55.761718  3134 net.cpp:226] conv1 needs backward computation.
I0406 11:09:55.761721  3134 net.cpp:228] label_data_1_split does not need backward computation.
I0406 11:09:55.761725  3134 net.cpp:228] data does not need backward computation.
I0406 11:09:55.761729  3134 net.cpp:270] This network produces output accuracy
I0406 11:09:55.761732  3134 net.cpp:270] This network produces output loss
I0406 11:09:55.761747  3134 net.cpp:283] Network initialization done.
I0406 11:09:55.761801  3134 solver.cpp:60] Solver scaffolding done.
I0406 11:09:55.762250  3134 socket.cpp:219] Waiting for valid port [0]
I0406 11:09:55.762285  3146 socket.cpp:158] Assigned socket server port [49578]
I0406 11:09:55.763015  3146 socket.cpp:171] Socket Server ready [0.0.0.0]
I0406 11:09:55.772425  3134 socket.cpp:219] Waiting for valid port [49578]
I0406 11:09:55.772439  3134 socket.cpp:227] Valid port found [49578]
I0406 11:09:55.772455  3134 CaffeNet.cpp:186] Socket adapter: ip-172-31-39-229:49578
I0406 11:09:55.772732  3134 CaffeNet.cpp:325] 0-th Socket addr: ip-172-31-39-229:49578
I0406 11:09:55.772750  3134 CaffeNet.cpp:325] 1-th Socket addr: 
I0406 11:09:55.772763  3134 JniCaffeNet.cpp:110] 0-th local addr: ip-172-31-39-229:49578
I0406 11:09:55.772774  3134 JniCaffeNet.cpp:110] 1-th local addr: 
16/04/06 11:09:55 INFO Executor: Finished task 1.0 in stage 0.0 (TID 1). 976 bytes result sent to driver
16/04/06 11:09:56 INFO CoarseGrainedExecutorBackend: Got assigned task 2
16/04/06 11:09:56 INFO Executor: Running task 0.0 in stage 1.0 (TID 2)
16/04/06 11:09:56 INFO TorrentBroadcast: Started reading broadcast variable 2
16/04/06 11:09:56 INFO MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 1580.0 B, free 6.7 KB)
16/04/06 11:09:56 INFO TorrentBroadcast: Reading broadcast variable 2 took 10 ms
16/04/06 11:09:56 INFO MemoryStore: Block broadcast_2 stored as values in memory (estimated size 2.6 KB, free 9.2 KB)
16/04/06 11:09:56 INFO TorrentBroadcast: Started reading broadcast variable 1
16/04/06 11:09:56 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 97.0 B, free 9.3 KB)
16/04/06 11:09:56 INFO TorrentBroadcast: Reading broadcast variable 1 took 10 ms
16/04/06 11:09:56 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 392.0 B, free 9.7 KB)
I0406 11:09:56.094302  3134 common.cpp:61] 1-th string is NULL
I0406 11:09:56.094362  3134 socket.cpp:250] Trying to connect with ...[ip-172-31-39-230:50843]
I0406 11:09:56.096086  3134 socket.cpp:309] Connected to server [ip-172-31-39-230.us-west-2.compute.internal:50843] with client_fd [41]
I0406 11:09:56.097497  3146 socket.cpp:184] Accepted the connection from client [ip-172-31-39-230.us-west-2.compute.internal]
I0406 11:10:06.097164  3134 parallel.cpp:392] GPUs pairs 
I0406 11:10:06.100571  3148 MemoryInputAdapter.cpp:15] MemoryInputAdapter is used
I0406 11:10:06.103435  3149 data_transformer.cpp:25] Loading mean file from: mean.binaryproto
16/04/06 11:10:06 INFO Executor: Finished task 0.0 in stage 1.0 (TID 2). 936 bytes result sent to driver
16/04/06 11:10:06 INFO CoarseGrainedExecutorBackend: Got assigned task 5
16/04/06 11:10:06 INFO Executor: Running task 1.0 in stage 2.0 (TID 5)
16/04/06 11:10:06 INFO TorrentBroadcast: Started reading broadcast variable 3
16/04/06 11:10:06 INFO MemoryStore: Block broadcast_3_piece0 stored as bytes in memory (estimated size 2.1 KB, free 11.8 KB)
16/04/06 11:10:06 INFO TorrentBroadcast: Reading broadcast variable 3 took 11 ms
16/04/06 11:10:06 INFO MemoryStore: Block broadcast_3 stored as values in memory (estimated size 3.3 KB, free 15.2 KB)
16/04/06 11:10:06 INFO CacheManager: Partition rdd_6_1 not found, computing it
16/04/06 11:10:06 INFO CacheManager: Partition rdd_1_1 not found, computing it
16/04/06 11:10:06 INFO LmdbRDD: Processing partition 1
16/04/06 11:10:06 ERROR Executor: Exception in task 1.0 in stage 2.0 (TID 5)
java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:114)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:114)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.yahoo.ml.caffe.LmdbRDD.localLMDBFile(LmdbRDD.scala:180)
	at com.yahoo.ml.caffe.LmdbRDD.com$yahoo$ml$caffe$LmdbRDD$$openDB(LmdbRDD.scala:197)
	at com.yahoo.ml.caffe.LmdbRDD$$anon$1.<init>(LmdbRDD.scala:98)
	at com.yahoo.ml.caffe.LmdbRDD.compute(LmdbRDD.scala:96)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
16/04/06 11:10:06 INFO CoarseGrainedExecutorBackend: Got assigned task 7
16/04/06 11:10:06 INFO Executor: Running task 0.1 in stage 2.0 (TID 7)
16/04/06 11:10:06 INFO CacheManager: Partition rdd_6_0 not found, computing it
16/04/06 11:10:06 INFO CacheManager: Partition rdd_1_0 not found, computing it
16/04/06 11:10:06 INFO LmdbRDD: Processing partition 0
16/04/06 11:10:06 ERROR Executor: Exception in task 0.1 in stage 2.0 (TID 7)
java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:114)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:114)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.yahoo.ml.caffe.LmdbRDD.localLMDBFile(LmdbRDD.scala:180)
	at com.yahoo.ml.caffe.LmdbRDD.com$yahoo$ml$caffe$LmdbRDD$$openDB(LmdbRDD.scala:197)
	at com.yahoo.ml.caffe.LmdbRDD$$anon$1.<init>(LmdbRDD.scala:98)
	at com.yahoo.ml.caffe.LmdbRDD.compute(LmdbRDD.scala:96)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
16/04/06 11:10:06 INFO CoarseGrainedExecutorBackend: Got assigned task 8
16/04/06 11:10:06 INFO Executor: Running task 1.2 in stage 2.0 (TID 8)
16/04/06 11:10:06 INFO CacheManager: Partition rdd_6_1 not found, computing it
16/04/06 11:10:06 INFO CacheManager: Partition rdd_1_1 not found, computing it
16/04/06 11:10:06 INFO LmdbRDD: Processing partition 1
16/04/06 11:10:06 ERROR Executor: Exception in task 1.2 in stage 2.0 (TID 8)
java.lang.NullPointerException
	at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:114)
	at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:114)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at com.yahoo.ml.caffe.LmdbRDD.localLMDBFile(LmdbRDD.scala:180)
	at com.yahoo.ml.caffe.LmdbRDD.com$yahoo$ml$caffe$LmdbRDD$$openDB(LmdbRDD.scala:197)
	at com.yahoo.ml.caffe.LmdbRDD$$anon$1.<init>(LmdbRDD.scala:98)
	at com.yahoo.ml.caffe.LmdbRDD.compute(LmdbRDD.scala:96)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
16/04/06 11:10:06 INFO CoarseGrainedExecutorBackend: Driver commanded a shutdown

**Comment by rahulbhalerao001** [comment]
Could you paste your command, and prototxt file. Also based on what I have seen, the same stderr of executors (accessible from spark ui) provides additional information about the error.

**Comment by junshi15** [comment]
Your lmdb files are local, not on HDFS? At one point, we introduced a bug with local lmdb files. This has been fixed with the following PR, https://github.com/yahoo/CaffeOnSpark/pull/42

Please update your code if it is affected by this.

**Comment by zokri** [comment]
Hi junish, i'm using you latest version(0.1.2(i think), and as far as i saw, thae changes you made are in the code already, and still i go this error...

my train prototxt:
name: "caffenet"
layer {
  name: "data"
  type: "MemoryData"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  source_class: "com.yahoo.ml.caffe.LMDB" 
  memory_data_param {
    source: "file:///root/CaffeOnSpark/data/faces2/TrainLmdb/"
    batch_size: 64
    channels: 3
    height: 227
    width: 227
    share_in_parallel: false
  }
  transform_param {
    mean_file: "mean.binaryproto"
  }
}
layer {
  name: "data"
  type: "MemoryData"
  top: "data"
  top: "label"
  include {
    phase: TEST
  }
  source_class: "com.yahoo.ml.caffe.LMDB"
  memory_data_param {
    source: "file:///root/CaffeOnSpark/data/faces2/ValLmdb/"
    batch_size: 100
    channels: 3
    height: 227
    width: 227
    share_in_parallel: false
  }
  transform_param {
    mean_file: "mean.binaryproto"
  }

}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 32
    pad: 2
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "gaussian"
      std: 0.0001
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "pool1"
  top: "pool1"
}
layer {
  name: "conv2"
  type: "Convolution"
  bottom: "pool1"
  top: "conv2"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 32
    pad: 2
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "relu2"
  type: "ReLU"
  bottom: "conv2"
  top: "conv2"
}
layer {
  name: "pool2"
  type: "Pooling"
  bottom: "conv2"
  top: "pool2"
  pooling_param {
    pool: AVE
    kernel_size: 3
    stride: 2
  }
}
layer {
  name: "conv3"
  type: "Convolution"
  bottom: "pool2"
  top: "conv3"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 64
    pad: 2
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "gaussian"
      std: 0.01
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "relu3"
  type: "ReLU"
  bottom: "conv3"
  top: "conv3"
}
layer {
  name: "pool3"
  type: "Pooling"
  bottom: "conv3"
  top: "pool3"
  pooling_param {
    pool: AVE
    kernel_size: 3
    stride: 2
  }
}
layer {
  name: "ip1"
  type: "InnerProduct"
  bottom: "pool3"
  top: "ip1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  inner_product_param {
    num_output: 64
    weight_filler {
      type: "gaussian"
      std: 0.1
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "ip2"
  type: "InnerProduct"
  bottom: "ip1"
  top: "ip2"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  inner_product_param {
    num_output: 2
    weight_filler {
      type: "gaussian"
      std: 0.1
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "accuracy"
  type: "Accuracy"
  bottom: "ip2"
  bottom: "label"
  top: "accuracy"
  include {
    phase: TEST
  }
}
layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "ip2"
  bottom: "label"
  top: "loss"
}

solver:

# The train/test net protocol buffer definition
net: "train.prototxt"
# test_iter specifies how many forward passes the test should carry out.
# In the case of MNIST, we have test batch size 100 and 100 test iterations,
# covering the full 10,000 testing images.
test_iter: 100
# Carry out testing every 500 training iterations.
test_interval: 500
# The base learning rate, momentum and the weight decay of the network.
base_lr: 0.001
momentum: 0.9
weight_decay: 0.004
# The learning rate policy
lr_policy: "fixed"
# Display every 100 iterations
display: 100
# The maximum number of iterations
max_iter: 4000
# snapshot intermediate results
snapshot: 4000
snapshot_format: HDF5
snapshot_prefix: "caffenet_train"
# solver mode: CPU or GPU
solver_mode: GPU

**Comment by junshi15** [comment]
Does it work for you with cifar-10 dataset (or mnist if you have not tried cigar-10)?
Your prototxt looks fine. 

Your launch command:
1) please specify "train" or "test" only, one at a time.
2) please add configs of executor/driver memory and memory overhead. Please refer to https://github.com/yahoo/CaffeOnSpark/issues/32 for details.

**Comment by zokri** [comment]
yes, for cifar and minst it works...

**Comment by zokri** [comment]
Hey guys, just for the update,
HDFS type works fine....(with same configuration)

**Comment by junshi15** [comment]
Oh, so you are sure you have the latest code, including this fix https://github.com/yahoo/CaffeOnSpark/pull/42

I thought we fix this local file issue, I will take another look when I get a chance.

**Comment by zokri** [comment]
yeah for sure, i checked the files you mentioned...

**Comment by anfeng** [comment]
@zokri can you re-run your training w/ latest AMI (ami-fe59d48d)? I just created it from our source code, and verified it works for MNIST and Cifar10 w/ 2 executors using g2.2xlarge. See the updated [EC2 guide](https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_EC2)

In your net definition file, you may want to change "file:///" to "file:/" as well.

**Comment by anfeng** [comment]
With the latest PR #59, this issue should be closed.
