### ISSUE TITLE
BUILD SUCCESS, but error follows.

### ISSUE THREAD

**Issue by arundasan91** [yahoo/CaffeOnSpark#60]
Hello there. First of all thank you guys for developing CaffeOnSpark. It is a great step in the right direction.

I was able to build CaffeOnSpark successfully:
```
[INFO] caffe ............................................. SUCCESS [0.001s]
[INFO] caffe-distri ...................................... SUCCESS [1:57.821s]
[INFO] caffe-grid ........................................ SUCCESS [3:05.423s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5:03.547s
[INFO] Finished at: Sat Apr 23 21:36:26 UTC 2016
[INFO] Final Memory: 55M/396M
```
The Issue:
However, an error follows it installation stops. Is this something that I should worry about ?
```
jar -xvf caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar META-INF/native/linux64/liblmdbjni.so
 inflated: META-INF/native/linux64/liblmdbjni.so
mv META-INF/native/linux64/liblmdbjni.so /home/cc/CaffeOnSpark/caffe-distri/distribute/lib
cp -r /home/cc/CaffeOnSpark/caffe-public/python/caffe /home/cc/CaffeOnSpark/caffe-grid/src/main/python/
cd /home/cc/CaffeOnSpark/caffe-grid/src/main/python/; zip -r caffeonsparkpythonapi  *; mv caffeonsparkpythonapi.zip /home/cc/CaffeOnSpark/caffe-grid/target/;cd /home/cc/CaffeOnSpark
/bin/sh: 1: zip: not found
mv: cannot stat ‘caffeonsparkpythonapi.zip’: No such file or directory
```

Thanks !

**Comment by junshi15** [comment]
Can you check what's in the directory "/home/cc/CaffeOnSpark/caffe-grid/src/main/python/"? i.e.
ls /home/cc/CaffeOnSpark/caffe-grid/src/main/python/

if you manually run "zip -r caffeonsparkpythonapi  *" under that directory, do you see caffeonsparkpythonapi.zip?

If you are not going to use iPython note book, then this file does not matter.

**Comment by arundasan91** [comment]
Oh my ! 
```zip``` was not installed. I installed unzip and blindly believed zip would be packaged as well.
The files are being zipped now. 

Thank You. This was trivial, I should have checked it properly.

However, when I am trying to run an example, I am getting this error:
```
cc@spark00:~/CaffeOnSpark/caffe-grid/src/main/python/examples$ python MultiClassLogisticRegression.py
Traceback (most recent call last):
  File "MultiClassLogisticRegression.py", line 7, in <module>
    from com.yahoo.ml.caffe.CaffeOnSpark import CaffeOnSpark
ImportError: No module named com.yahoo.ml.caffe.CaffeOnSpark
```

Could you please help me with this ?

**Comment by arundasan91** [comment]
I have some configuration issues with spark itself. I will work on it. Closing this one for now. 

Thank you for your support.
