### ISSUE TITLE
How to increase CPU usage per executor?

### ISSUE THREAD

**Issue by markyeh** [yahoo/CaffeOnSpark#62]
Hi,

I tried to evaluate CaffeOnSpark on CPU mode with Ethernet.

The YARN cluster mode worked fine with my 4 nodes(32 CPU cores per node) environment.

But I observed the CPU usage of each executor only take 3 cores no matter which number of "--executor-cores" is allocated (I've tried 8 and 16).

I also tried to set "-devices NUM" to CaffeOnSpark, but I got fail except the default "-devices 1" on CPU mode.

Could you provide any tips for using more CPU cores per executor? thank you.

**Comment by anfeng** [comment]
For CPU mode, you should try to launch multiple executors per node. To do that, you want to use a small value for --executor-cores.

**Comment by markyeh** [comment]
OK, thanks for your reply.
