### ISSUE TITLE
coding mistake in ImageDataSource.scala

### ISSUE THREAD

**Issue by yteric** [yahoo/CaffeOnSpark#63]
caffe-grid/src/main/scala/com/yahoo/ml/caffe/ImageDataSource.scala:121
` if (mat.width() != sample_width || mat.height() != sample_width) {`
the second `sample_width` should be `sample_height`

**Comment by junshi15** [comment]
Thanks for your comment. We will fix it shortly.

**Comment by anfeng** [comment]
This issue is closed w/ PR #64
