### ISSUE TITLE
Wiki typo

### ISSUE THREAD

**Issue by jsongcse** [yahoo/CaffeOnSpark#68]
For YARN clusters, I think
`hadoop fs -rm -r -f ${CAFFE_ON_SPARK}/mnist_features_result`

should be
`hadoop fs -rm -r -f hdfs:///mnist_features_result`

**Comment by junshi15** [comment]
It works on our system. I thought "hdfs://" is prepended automatically if the HDFS is set properly.

**Comment by jsongcse** [comment]
@junshi15 Oh, does it work on your system? I didn't know that.

But still, I think there should be uniformity among commands so that the manual will be easier to understand. For example, currently the two lines in the manual look like this:

`hadoop fs -rm -f hdfs:///mnist.model`
`hadoop fs -rm -r -f ${CAFFE_ON_SPARK}/mnist_features_result`

**Comment by junshi15** [comment]
sure, we will fix that in the next update. Or you are welcome to send a pull-request.

**Comment by anfeng** [comment]
Thanks @jsongcse. [YARN doc](https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_yarn) is now fixed.
