### ISSUE TITLE
Any design details to be exposed about CaffeOnSpark?

### ISSUE THREAD

**Issue by fanshiqing** [yahoo/CaffeOnSpark#73]
I found this project really useful and want to do some interesting things with it as well as some possible pull requests. While it seems that the related materials is so limited that we have to bite the bullet to read the source code for a systematic understanding. That's really not an easy effort and worse we may produce some misunderstanding during this process.

So my question is that i**s there any design details to be exposed about this project in the near future? Or may you open source some detailed framework references just like [caffe's](http://caffe.berkeleyvision.org/tutorial/)**. 

Really appreciate for any useful comment!

**Comment by princhenee** [comment]
This would be useful for new players.

**Comment by fanshiqing** [comment]
@anfeng @mriduljain

**Comment by anfeng** [comment]
It is unclear what you are looking for. Can you ask specific questions?

BTW, we are giving talks about CaffeOnSpark at both Spark Summit and Hadoop Summit this month. We are happy to meet user community and answer questions in person.

Andy Feng
