### ISSUE TITLE
Installation Error while building CaffeOnSpark

### ISSUE THREAD

**Issue by LinHungShi** [yahoo/CaffeOnSpark#75]
I have run caffe and spark successfully. However, when I am building caffeonspark, it shows many warning and errors. I can't understand what these things mean and have no idea what to do. Could someone helps me?

cd caffe-public; make proto; make -j4 -e distribute; cd ..
make[1]: Nothing to be done for `proto'.
NVCC src/caffe/layers/absval_layer.cu
NVCC src/caffe/layers/base_data_layer.cu
NVCC src/caffe/layers/batch_norm_layer.cu
NVCC src/caffe/layers/batch_reindex_layer.cu
nvcc fatal   : The version ('70300') of the host compiler ('Apple clang') is not supported
nvcc fatal   : The version ('70300') of the host compiler ('Apple clang') is not supported
nvcc fatal   : The version ('70300') of the host compiler ('Apple clang') is not supported
make[1]: *** [.build_release/cuda/src/caffe/layers/batch_reindex_layer.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [.build_release/cuda/src/caffe/layers/base_data_layer.o] Error 1
make[1]: *** [.build_release/cuda/src/caffe/layers/absval_layer.o] Error 1
nvcc fatal   : The version ('70300') of the host compiler ('Apple clang') is not supported
make[1]: *** [.build_release/cuda/src/caffe/layers/batch_norm_layer.o] Error 1
export LD_LIBRARY_PATH="/home/y/lib64:/home/y/lib64/mkl/intel64:/Users/Red_Hair/Downloads/CaffeOnSpark/caffe-public/distribute/lib:/Users/Red_Hair/Downloads/CaffeOnSpark/caffe-distri/distribute/lib:/usr/lib64:/lib64 "; mvn -B package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.yahoo.ml:caffe-grid:jar:0.1-SNAPSHOT
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] caffe
[INFO] caffe-distri
[INFO] caffe-grid
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building caffe 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building caffe-distri 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (proto) @ caffe-distri ---
[INFO] Executing tasks

protoc:
     [exec] make[1]: *** No rule to make target `../caffe-public/distribute/proto/caffe.proto', needed by `src/main/java/caffe/Caffe.java'.  Stop.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] caffe .............................................. SUCCESS [  0.005 s]
[INFO] caffe-distri ....................................... FAILURE [  3.871 s]
[INFO] caffe-grid ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.188 s
[INFO] Finished at: 2016-06-08T15:03:14+08:00
[INFO] Final Memory: 8M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (proto) on project caffe-distri: An Ant BuildException has occured: exec returned: 2
[ERROR] around Ant part ...<exec failonerror="true" dir="/Users/Red_Hair/Downloads/CaffeOnSpark/caffe-distri" executable="make">... @ 5:104 in /Users/Red_Hair/Downloads/CaffeOnSpark/caffe-distri/target/antrun/build-protoc.xml
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :caffe-distri
make: *** [build] Error 1

**Comment by mriduljain** [comment]
Please check similar bug/thread. You need protobuf

**Comment by LinHungShi** [comment]
but I have installed protobuf. No matter which version I use, 2.6.0 or 2.5 it doesn't work

**Comment by LinHungShi** [comment]
I remake the file , and I still get errors. One of lines says 
```
Undefined symbols for architecture x86_64:
  "caffe::P2PSync<float>::run(std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
      train() in caffe.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
any idea?

**Comment by mriduljain** [comment]
Please check if your LD_LIBRARY_PATH is set correctly or not

**Comment by LinHungShi** [comment]
you mean these lines? I suppose they should be done after successfully build

export LD_LIBRARY_PATH=${CAFFE_ON_SPARK}/caffe-public/distribute/lib:${CAFFE_ON_SPARK}/caffe-distri/distribute/lib
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/cuda-7.0/lib64:/usr/local/mkl/lib/intel64/

**Comment by LinHungShi** [comment]
It seems I don't have caffe.proto file. Could anyone help me. Can I just copy one and put it in the directory?

**Comment by mriduljain** [comment]
Do you have protoc available in command line ?
If so cc caffe-public and make proto

**Comment by mriduljain** [comment]
Well the linker will look for files in LD_LIBRARY_PATH

**Comment by LinHungShi** [comment]
How could I know whether protoc is available in command line?
I manually copy and install the files except python, to the distribute. However, I am stuck in the tests

```
Failed tests:   setUp(com.yahoo.ml.jcaffe.CaffeNetTest): /Users/Red_Hair/Downloads/CaffeOnSpark/caffe-distri/.build_release/lib/libcaffedistri.jnilib: dlopen(/Users/Red_Hair/Downloads/CaffeOnSpark/caffe-distri/.build_release/lib/libcaffedistri.jnilib, 1): Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.9.dylib(..)
  testAllocate(com.yahoo.ml.jcaffe.FloatBlobTest): com.yahoo.ml.jcaffe.BaseObject
  testBasic(com.yahoo.ml.jcaffe.FloatBlobTest): com.yahoo.ml.jcaffe.BaseObject
  testCopy(com.yahoo.ml.jcaffe.FloatBlobTest): com.yahoo.ml.jcaffe.BaseObject
  basicDataTest(com.yahoo.ml.jcaffe.MatTest): com.yahoo.ml.jcaffe.BaseObject
  basicTest(com.yahoo.ml.jcaffe.MatTest): com.yahoo.ml.jcaffe.BaseObject
  matChannelsTest(com.yahoo.ml.jcaffe.MatTest): com.yahoo.ml.jcaffe.BaseObject
  matResizeDecodeTest(com.yahoo.ml.jcaffe.MatTest): com.yahoo.ml.jcaffe.BaseObject
  setUp(com.yahoo.ml.jcaffe.TransformTest): com.yahoo.ml.jcaffe.BaseObject

Tests run: 17, Failures: 9, Errors: 0, Skipped: 7

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] caffe .............................................. SUCCESS [  0.004 s]
[INFO] caffe-distri ....................................... FAILURE [02:00 min]
[INFO] caffe-grid ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:00 min
[INFO] Finished at: 2016-06-09T21:54:16+08:00
[INFO] Final Memory: 25M/452M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project caffe-distri: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/Red_Hair/Downloads/CaffeOnSpark/caffe-distri/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :caffe-distri
make: *** [build] Error 1
```

**Comment by mriduljain** [comment]
Ok you are using OS X in which case set DYLD_LIBRARY_PATH
Also you may need to specify the lib path for protobuf in your
Makefile.config in caffe-public

**Comment by LinHungShi** [comment]
I am not familiar with unix and linux system. Could you please explain it in more details. Like setting DYLD_LIBRARY_PATH, and how to specify lib path for protobuf. Thank you

**Comment by LinHungShi** [comment]
I follow this page to set DYLD_LIBRARY_PATH, but it doesn't work

**Comment by LinHungShi** [comment]
I add libprotobuf9.dylib to DYLD_LIBRARY_PTH , but it doesn't work. Which path does it search ?

**Comment by LinHungShi** [comment]
I should clarify what I have done so far.
First I follow the steps here https://github.com/yahoo/CaffeOnSpark/wiki/GetStarted_local_osx
however, when I use make build, it says 

> "caffe::P2PSync<float>::run(std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
>       train() in caffe.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [.build_release/tools/caffe.bin] Error 1
> make[1]: *** Waiting for unfinished jobs....
> export LD_LIBRARY_PATH="/home/y/lib64:/home/y/lib64/mkl/intel64:/Users/Red_Hair/Downloads/CaffeOnSpark/caffe-public/distribute/lib:/Users/Red_Hair/Downloads/CaffeOnSpark/caffe-distri/distribute/lib:/usr/lib64:/lib64 "; mvn -B package
> [INFO] Scanning for projects...
> [WARNING] 
> [WARNING] Some problems were encountered while building the effective model for com.yahoo.ml:caffe-grid:jar:0.1-SNAPSHOT
> [WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
> [WARNING] 
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING] 
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING] 
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Build Order:
> [INFO] 
> [INFO] caffe
> [INFO] caffe-distri
> [INFO] caffe-grid
> [INFO]                                                                         
> [INFO] ------------------------------------------------------------------------
> [INFO] Building caffe 0.1-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO]                                                                         
> [INFO] ------------------------------------------------------------------------
> [INFO] Building caffe-distri 0.1-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO] 
> [INFO] --- maven-antrun-plugin:1.7:run (proto) @ caffe-distri ---
> [INFO] Executing tasks
> 
> protoc:
>      [exec] make[1]: *** No rule to make target `../caffe-public/distribute/proto/caffe.proto', needed by `src/main/java/caffe/Caffe.java'.  Stop.

Then I follow the steps in Makefile in caffe-public to manually copy and install files to distribute. then when I make build again, it says

> cd caffe-public; make proto; make -j4 -e distribute; cd ..
> make[1]: Nothing to be done for `proto'.
> CXX/LD -o .build_release/tools/caffe.bin
> CXX/LD -o .build_release/tools/device_query.bin
> CXX/LD -o .build_release/tools/extract_features.bin
> CXX/LD -o .build_release/tools/finetune_net.bin
> clangclangclang: : : warningwarningwarning: : : argument unused during compilation: '-pthread'argument unused during compilation: '-pthread'argument unused during compilation: '-pthread'
> 
> 
> clang: warning: argument unused during compilation: '-pthread'
> Undefined symbols for architecture x86_64:
>   "caffe::P2PSync<float>::run(std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
>       train() in caffe.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [.build_release/tools/caffe.bin] Error 1
> make[1]: *** Waiting for unfinished jobs....
> export LD_LIBRARY_PATH="/home/y/lib64:/home/y/lib64/mkl/intel64:/Users/Red_Hair/Downloads/CaffeOnSpark/caffe-public/distribute/lib:/Users/Red_Hair/Downloads/CaffeOnSpark/caffe-distri/distribute/lib:/usr/lib64:/lib64 "; mvn -B package
> [INFO] Scanning for projects...
> [WARNING] 
> [WARNING] Some problems were encountered while building the effective model for com.yahoo.ml:caffe-grid:jar:0.1-SNAPSHOT
> [WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
> [WARNING] 
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING] 
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING] 
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Build Order:
> [INFO] 
> [INFO] caffe
> [INFO] caffe-distri
> [INFO] caffe-grid
> [INFO]                                                                         
> [INFO] ------------------------------------------------------------------------
> [INFO] Building caffe 0.1-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO]                                                                         
> [INFO] ------------------------------------------------------------------------
> [INFO] Building caffe-distri 0.1-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO] 
> [INFO] --- maven-antrun-plugin:1.7:run (proto) @ caffe-distri ---
> [INFO] Executing tasks
> 
> protoc:
>      [exec] PROTOC ../caffe-public/distribute/proto/caffe.proto
> [INFO] Executed tasks
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.0:compile (compile-generator) @ caffe-distri ---
> [INFO] Changes detected - recompiling the module!
> [WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
> [INFO] Compiling 10 source files to /Users/Red_Hair/Downloads/CaffeOnSpark/caffe-distri/target/classes
> [INFO] 
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ caffe-distri ---
> [WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
> [INFO] skip non existing resourceDirectory /Users/Red_Hair/Downloads/CaffeOnSpark/caffe-distri/src/main/resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ caffe-distri ---
> [INFO] Changes detected - recompiling the module!
> [WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
> [INFO] Compiling 10 source files to /Users/Red_Hair/Downloads/CaffeOnSpark/caffe-distri/target/classes
> [INFO] 
> [INFO] --- maven-antrun-plugin:1.7:run (make) @ caffe-distri ---
> [INFO] Executing tasks
> 
> make:
>      [exec] javah -d include/jni -force -cp target/classes \
>      [exec] 	com.yahoo.ml.jcaffe.CaffeNet
>      [exec] javah -d include/jni -force -cp target/classes \
>      [exec] 	com.yahoo.ml.jcaffe.FloatArray
>      [exec] javah -d include/jni -force -cp target/classes \
>      [exec] 	com.yahoo.ml.jcaffe.FloatBlob
>      [exec] javah -d include/jni -force -cp target/classes \
>      [exec] 	com.yahoo.ml.jcaffe.FloatDataTransformer
>      [exec] javah -d include/jni -force -cp target/classes \
>      [exec] 	com.yahoo.ml.jcaffe.Mat
>      [exec] javah -d include/jni -force -cp target/classes \
>      [exec] 	com.yahoo.ml.jcaffe.MatVector
>      [exec] CXX src/main/cpp/CaffeNet.cpp
>      [exec] CXX src/main/cpp/common.cpp
>      [exec] CXX src/main/cpp/jni/JniCaffeNet.cpp
>      [exec] CXX src/main/cpp/jni/JniFloatArray.cpp
>      [exec] CXX src/main/cpp/jni/JniFloatBlob.cpp
>      [exec] CXX src/main/cpp/jni/JniFloatDataTransformer.cpp
>      [exec] CXX src/main/cpp/jni/JniMat.cpp
>      [exec] CXX src/main/cpp/jni/JniMatVector.cpp
>      [exec] CXX src/main/cpp/util/blocking_queue_extra.cpp
>      [exec] In file included from src/main/cpp/util/blocking_queue_extra.cpp:4:
>      [exec] ../caffe-public/src/caffe/util/blocking_queue.cpp:50:7: warning: unused typedef 'INVALID_REQUESTED_LOG_SEVERITY' [-Wunused-local-typedef]
>      [exec]       LOG_EVERY_N(INFO, 1000)<< log_on_wait;
>      [exec]       ^
>      [exec] /usr/local/include/glog/logging.h:917:30: note: expanded from macro 'LOG_EVERY_N'
>      [exec]                              INVALID_REQUESTED_LOG_SEVERITY);           \
>      [exec]                              ^
>      [exec] 1 warning generated.
>      [exec] CXX src/main/cpp/util/InputAdapter.cpp
>      [exec] CXX src/main/cpp/util/MemoryInputAdapter.cpp
>      [exec] CXX src/main/cpp/util/mini_cluster.cpp
>      [exec] CXX src/main/cpp/util/parallel_cpu.cpp
>      [exec] CXX src/main/cpp/util/rdma.cpp
>      [exec] CXX src/main/cpp/util/rdma_sync.cpp
>      [exec] CXX src/main/cpp/util/socket.cpp
>      [exec] CXX src/main/cpp/util/socket_sync.cpp
>      [exec] CXX src/main/cpp/util/socket_sync_cpu.cpp
>      [exec] AR -o .build_release/lib/libcaffedistri.a
>      [exec] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .build_release/lib/libcaffedistri.a(rdma.o) has no symbols
>      [exec] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .build_release/lib/libcaffedistri.a(rdma_sync.o) has no symbols
>      [exec] clang: warning: argument unused during compilation: '-pthread'
>      [exec] LD -o .build_release/lib/libcaffedistri.jnilib .build_release/src/main/cpp/CaffeNet.o .build_release/src/main/cpp/common.o .build_release/src/main/cpp/jni/JniCaffeNet.o .build_release/src/main/cpp/jni/JniFloatArray.o .build_release/src/main/cpp/jni/JniFloatBlob.o .build_release/src/main/cpp/jni/JniFloatDataTransformer.o .build_release/src/main/cpp/jni/JniMat.o .build_release/src/main/cpp/jni/JniMatVector.o .build_release/src/main/cpp/util/blocking_queue_extra.o .build_release/src/main/cpp/util/InputAdapter.o .build_release/src/main/cpp/util/MemoryInputAdapter.o .build_release/src/main/cpp/util/mini_cluster.o .build_release/src/main/cpp/util/parallel_cpu.o .build_release/src/main/cpp/util/rdma.o .build_release/src/main/cpp/util/rdma_sync.o .build_release/src/main/cpp/util/socket.o .build_release/src/main/cpp/util/socket_sync.o .build_release/src/main/cpp/util/socket_sync_cpu.o
>      [exec] CXX src/main/cpp/tools/caffe_mini_cluster.cpp
>      [exec] make[1]: *** [.build_release/src/main/cpp/tools/caffe_mini_cluster.o] Error 1
>      [exec] src/main/cpp/tools/caffe_mini_cluster.cpp:285:14: error: use of undeclared identifier 'bp'
>      [exec]     } catch (bp::error_already_set) {
>      [exec]              ^
>      [exec] src/main/cpp/tools/caffe_mini_cluster.cpp:286:7: error: use of undeclared identifier 'PyErr_Print'
>      [exec]       PyErr_Print();
>      [exec]       ^
>      [exec] 2 errors generated.
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO] 
> [INFO] caffe .............................................. SUCCESS [  0.004 s]
> [INFO] caffe-distri ....................................... FAILURE [01:38 min]
> [INFO] caffe-grid ......................................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 01:38 min
> [INFO] Finished at: 2016-06-09T22:43:30+08:00
> [INFO] Final Memory: 19M/372M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (make) on project caffe-distri: An Ant BuildException has occured: exec returned: 2
> [ERROR] around Ant part ...<exec failonerror="true" dir="/Users/Red_Hair/Downloads/CaffeOnSpark/caffe-distri" executable="make">... @ 5:104 in /Users/Red_Hair/Downloads/CaffeOnSpark/caffe-distri/target/antrun/build-make.xml
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <goals> -rf :caffe-distri
> make: *** [build] Error 1

Finally, I disable python installation in Makefile.config, an remake it again, then I got the test error I posted above. How should I do? Can I avoid installing python?

**Comment by LinHungShi** [comment]
It seems I need to use libprotobuf.9.dylib, but protobuf 2.5.0 uses libprotobuf.8.dylib

**Comment by LinHungShi** [comment]
I post two error.log that is caffe-dist, the first is the error.log I get because of lack of libprotobuf.9.dylib
the second one is the error.log after I put libprotobuf.9.dylib into /usr/local/opt/protobuf/lib/
