### ISSUE TITLE
Spark 2.0 Branch / Support [Enhancement]

### ISSUE THREAD

**Issue by javadba** [yahoo/CaffeOnSpark#78]
I added a PR for Spark 2.0 using the SparkSession instead of SparkContext. In addition the libraries were moved to scala 2.11 and hadoop 2.7.1 to be more in line with spark 2.X direction.  The tests were run and pass.

https://github.com/yahoo/CaffeOnSpark/pull/77

**Comment by mriduljain** [comment]
It would be great if you can make this backwards compatible

**Comment by javadba** [comment]
To be backwards compatible we would need to retain the SparkContext as the
input parameter to all the methods.  That is squarely contrary to Spark 2.X
.  2.X *is* a breaking change - so to be consistent it *is* a breaking
change here.

Now if you *really* want a non-breaking change I can add it in a separate
branch. Keep in mind it will be using deprecated api's in that case.

2016-06-08 11:39 GMT-07:00 mriduljain <notifications@github.com>:

**Comment by javadba** [comment]
fyi I have created said branch and looking to see if can make this happen. update l8r today.

**Comment by javadba** [comment]
Backwards compatibility is in place. Two methods are provided: using SparkSession or using SparkContext.  The updates are in the *same* branch to simplify our discussion.  Feel free to take look at the latest commit on the previously provided PR.

**Comment by mriduljain** [comment]
Thanks will go through and comment soon

**Comment by javadba** [comment]
I should clarify: the backwards compatibility applies *only to the consuming source code*: they do not need to be changed.  

The SparkSession class is included and thus *this change will not run against Spark 1.X*.   To truly achieve the backwards compatibility then we would need to add some shell scripts to manipulate the source files.  I do not believe that were worth it. Instead maintain in separate Spark 2.X branch.   At some point you decide to merge it into main and then the Spark 1.X becomes maintenance mode.

**Comment by javadba** [comment]
A new PR has been opened that simplifies the approach and provides full backwards compatibility via a maven profile.   https://github.com/yahoo/CaffeOnSpark/pull/79
Use

    mvn -Dspark2  <actions>  

to use Spark 2.x.  The actual versions of the following items are specified in that profile

    Spark  Scala Hadoop

**Comment by javadba** [comment]
I found a bug in #79 and am looking into it.

**Comment by javadba** [comment]
False alarm!  The reason is:  

If you first try the spark 1.X  via  

    mvn package

and *then* try  spark 2.X via

    mvn -Dspark2 package

it WILL fail. 

We need to do **clean** to get all the stuff recompiled.   So the following is required:

    mvn -Dspark2  clean package

**Comment by mriduljain** [comment]
I guess this pull request has been merged. Closing this. Thanks so much
