### ISSUE TITLE
error while building 

### ISSUE THREAD

**Issue by abhaymise** [yahoo/CaffeOnSpark#80]
while building i am getting following error :

src/main/cpp/tools/caffe_mini_cluster.cpp: In function ‘int main(int, char**)’:
     [exec] src/main/cpp/tools/caffe_mini_cluster.cpp:285:14: error: expected type-specifier before ‘bp’
     [exec]      } catch (bp::error_already_set) {
     [exec]               ^
     [exec] src/main/cpp/tools/caffe_mini_cluster.cpp:285:16: error: expected ‘)’ before ‘::’ token
     [exec]      } catch (bp::error_already_set) {
     [exec]              
     [exec]    ^
     [exec] src/main/cpp/tools/caffe_mini_cluster.cpp:285:16: error: expected ‘{’ before ‘::’ token
     [exec] src/main/cpp/tools/caffe_mini_cluster.cpp:285:16: error: ‘::error_already_set’ has not been declared
     [exec] src/main/cpp/tools/caffe_mini_cluster.cpp:285:35: error: expected ‘;’ before ‘)’ token
     [exec]      } catch (bp::error_already_set) {
     [exec]                                    ^
     [exec] src/main/cpp/tools/caffe_mini_cluster.cpp: In function ‘caffe::SolverAction::Enum GetRequestedAction(const string&)’:
     [exec] src/main/cpp/tools/caffe_mini_cluster.cpp:168:1: warning: control reaches end of non-void function [-Wreturn-type]
     [exec]  }
     [exec]  ^

My Makefile.config file looks like :
## cuDNN acceleration switch (uncomment to build with cuDNN).
USE_CUDNN := 1
## uncomment to disable IO dependencies and corresponding data layers
 USE_OPENCV := 1
## CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda
## For CUDA < 6.0, comment the *_50 lines for compatibility.
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
		-gencode arch=compute_20,code=sm_21 \
		-gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35 \
		-gencode arch=compute_50,code=sm_50 \
		-gencode arch=compute_50,code=compute_50
## open for OpenBlas
BLAS := atlas
## We need to be able to find Python.h and numpy/arrayobject.h.
##PYTHON_INCLUDE := /usr/include/python2.7 \
		/usr/lib/python2.7/dist-packages/numpy/core/include
## Verify anaconda location, sometimes it's in root.
 ANACONDA_HOME := /opt/anaconda2
 PYTHON_INCLUDE := $(ANACONDA_HOME)/include \
		 $(ANACONDA_HOME)/include/python2.7 \
		 $(ANACONDA_HOME)/lib/python2.7/site-packages/numpy/core/include \
## We need to be able to find libpythonX.X.so or .dylib.
##PYTHON_LIB := /usr/lib
 PYTHON_LIB := $(ANACONDA_HOME)/lib
## Uncomment to support layers written in Python (will link against Python libs)
 WITH_PYTHON_LAYER := 1
## Whatever else you find you need goes here.
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include
LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /usr/lib
## USE_PKG_CONFIG := 1
BUILD_DIR := build
DISTRIBUTE_DIR := distribute

## The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 0

## enable pretty build (comment to see full commands)
Q ?= @
INCLUDE_DIRS += /usr/lib/jvm/java-1.7.0-openjdk-amd64/include

Please help

**Comment by mriduljain** [comment]
I can't figure out from this. You can delete this file if you want as we do
not use it anywhere except local testing etc

**Comment by GnosisYu** [comment]
Please check the below link.
https://github.com/yahoo/CaffeOnSpark/issues/5
It looks Okay to remove caffe_mini_cluster.cpp. I succeeded in installing the caffeonspark after removal.

**Comment by abhaymise** [comment]
Thanks for your update.I will try this and let you know.

**Comment by abhaymise** [comment]
Thanks GnosisYu,
It worked for me as well.
I do not know the where do we use  caffe_mini_cluster.cpp.
As of now i am Ok with removing it.
