### ISSUE TITLE
Yarn executor ends at executor.CoarseGrainedExecutorBackend in CPU MODE

### ISSUE THREAD

**Issue by abhaymise** [yahoo/CaffeOnSpark#82]
I am trying to run given examples in distributed spark mode both with CPU and GPU but both jobs fail.

One with CPU mode gives following error 

16/06/10 14:42:29 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/06/10 14:42:29 INFO spark.SecurityManager: Changing view acls to: ubuntu
16/06/10 14:42:29 INFO spark.SecurityManager: Changing modify acls to: ubuntu
16/06/10 14:42:29 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(ubuntu); users with modify permissions: Set(ubuntu)
16/06/10 14:42:29 ERROR executor.CoarseGrainedExecutorBackend: RECEIVED SIGNAL 15: SIGTERM

**Comment by junshi15** [comment]
The error is most likely due to executor out of memory. You may want to increase your executor-memory and/or memoryOverhead.
