### ISSUE TITLE
errors about building

### ISSUE THREAD

**Issue by dahaichangge** [yahoo/CaffeOnSpark#87]
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/liutao/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[9919,31] cannot find symbol
  symbol:   class ProtocolStringList
  location: package com.google.protobuf
[ERROR] /home/liutao/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[8280,24] cannot find symbol
  symbol:   class ProtocolStringList
  location: package com.google.protobuf
[ERROR] /home/liutao/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[5761,31] cannot find symbol
  symbol:   class ProtocolStringList
.........................................

[ERROR] /home/liutao/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[5655,26] cannot find symbol
  symbol:   method getUnmodifiableView()
  location: variable input_ of type com.google.protobuf.LazyStringList
[ERROR] /home/liutao/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[6395,26] cannot find symbol
  symbol:   method getUnmodifiableView()
  location: variable input_ of type com.google.protobuf.LazyStringList
[ERROR] /home/liutao/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[6718,22] cannot find symbol
  symbol:   method getUnmodifiableView()
................................................

[ERROR] /home/liutao/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[55667,38] cannot find symbol
  symbol:   method getUnmodifiableView()
  location: variable dataframeColumnSelect_ of type com.google.protobuf.LazyStringList
[ERROR] /home/liutao/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[70179,28] cannot find symbol
  symbol:   method getUnmodifiableView()
  location: variable bottom_ of type com.google.protobuf.LazyStringList
[ERROR] /home/liutao/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[70182,22] cannot find symbol
  symbol:   method getUnmodifiableView()
  location: variable top_ of type com.google.protobuf.LazyStringList
[ERROR] /home/liutao/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[70203,26] cannot find symbol
  symbol:   method getUnmodifiableView()
  location: variable param_ of type com.google.protobuf.LazyStringList
[ERROR] /home/liutao/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[72536,28] cannot find symbol
  symbol:   method getUnmodifiableView()
  location: variable bottom_ of type com.google.protobuf.LazyStringList
[ERROR] /home/liutao/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[72541,22] cannot find symbol
  symbol:   method getUnmodifiableView()
  location: variable top_ of type com.google.protobuf.LazyStringList
[ERROR] /home/liutao/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[72581,26] cannot find symbol
  symbol:   method getUnmodifiableView()
  location: variable param_ of type com.google.protobuf.LazyStringList
[ERROR] /home/liutao/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[73159,23] cannot find symbol
  symbol:   method getUnmodifiableView()
  location: variable bottom_ of type com.google.protobuf.LazyStringList
[ERROR] /home/liutao/CaffeOnSpark/caffe-distri/src/main/java/caffe/Caffe.java:[73252,20] cannot find symbol
  symbol:   method getUnmodifiableView()
............................................

Is there anyone can do me a favor?

**Comment by anfeng** [comment]
It seems that you have an issue w/ protobuf. Which protobuf version do you use? It should be 2.5.0.

**Comment by dahaichangge** [comment]
And another error about building is：

....................
[INFO] caffe .............................................. SUCCESS [  0.001 s]
[INFO] caffe-distri ....................................... FAILURE [  1.074 s]
[INFO] caffe-grid ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.364 s
[INFO] Finished at: 2016-06-20T10:13:29+08:00
[INFO] Final Memory: 39M/3926M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (proto) on project caffe-distri: An Ant BuildException has occured: exec returned: 2
[ERROR] around Ant part ...<exec dir="/home/liutao/CaffeOnSpark/caffe-distri" executable="make" failonerror="true">... @ 5:91 in /home/liutao/CaffeOnSpark/caffe-distri/target/antrun/build-protoc.xml
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :caffe-distri
Makefile:9: recipe for target 'build' failed
make: *** [build] Error 1
root@master:/home/liutao/CaffeOnSpark# mvn --version
Picked up _JAVA_OPTIONS: -Xms4g -
.......................................



Can you help me?I would appreciate it if you could help me.

**Comment by desertnaut** [comment]
I have a similar issue with the last one reported above by @dahaichangge. I have successfully compiled standalone Caffe, and my protobuf version is indeed 2.5.0. I am in an Oracle Linux machine.
```
[...]
touch python/caffe/proto/__init__.py
AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0-rc3
/usr/bin/ld: cannot find -libverbs
/usr/bin/ld: cannot find -libumad
collect2: error: ld returned 1 exit status
make[1]: *** [.build_release/lib/libcaffe.so.1.0.0-rc3] Error 1
[...]
[INFO] Executing tasks

protoc:
     [exec] make[1]: Entering directory `/home/ctsats/CaffeOnSpark/caffe-distri'
     [exec] make[1]: Leaving directory `/home/ctsats/CaffeOnSpark/caffe-distri'
     [exec] make[1]: *** No rule to make target `../caffe-public/distribute/proto/caffe.proto', needed by `src/main/java/caffe/Caffe.java'.  Stop.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] caffe ............................................. SUCCESS [0.002s]
[INFO] caffe-distri ...................................... FAILURE [1.421s]
[INFO] caffe-grid ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[...]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (proto) on project caffe-distri: An Ant BuildException has occured: exec returned: 2
[ERROR] around Ant part ...<exec dir="/home/ctsats/CaffeOnSpark/caffe-distri" executable="make" failonerror="true">... @ 5:91 in /home/ctsats/CaffeOnSpark/caffe-distri/target/antrun/build-protoc.xml
[ERROR] -> [Help 1]
[...]
make: *** [build] Error 1
```
I had previously deleted `caffe_mini_cluster.cpp` which was causing other problems, as suggested in the issue https://github.com/yahoo/CaffeOnSpark/issues/80 .
Any help would be greatly appreciated!
Many thanks in advance.

**Comment by desertnaut** [comment]
Well, I commented out INFINIBAND := 1 in Make.config, and the build was successful. I had initially enabled it as my cluster is connected via Infiniband. Does this mean I will face problems ahead?

**Comment by junshi15** [comment]
the errors below shows the infiniband libraries were not found. Maybe you need to set the path in Makefile.
/usr/bin/ld: cannot find -libverbs
/usr/bin/ld: cannot find -libumad

If you comment out INIFINIBAND :=1, you won't be able to use INFINIBAND, just regular ethernet, if you have one.

**Comment by desertnaut** [comment]
Thanks for the reply. It turns out that our virtual servers are not actually "aware" of the physical infiniband infrastructure - to them it seems just like a quick ethernet. I have now successfuly built all components and passed the built-in tests. I am facing another problem, however, for which I'll open a new thread.
Thanks again

**Comment by cimenx** [comment]
i had the same problem as @dahaichangge  in https://github.com/yahoo/CaffeOnSpark/issues/87#issue-160880892
i try installing protobuf using pip install -U -r python/requirements.txt in folder caffe-public.
i'm using protobuf 3.0.0

**Comment by anfeng** [comment]
Please use protobuf 2.5.0. 

You are welcome to propose a PR to support protobuf 3.0.0. We will need to adjust pom.xml files, and likely no code change needed.
