### ISSUE TITLE
Error while building - run (proto) on project caffe distri

### ISSUE THREAD

**Issue by helloFromTheOtherSide** [yahoo/CaffeOnSpark#89]
Hy!

I am getting this error when running 'make build' command.
I have installed the version 2.5.0 for protoc and maven3.
There is no other message beside the one from beneath, and i can't guess what's causing the error.
I set Makefile.config in order to use only CPU, without OpenCV and using OpenBLAS. 
Can you help me find out the cause with some suggestions ?

[INFO] Building caffe-distri 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (proto) @ caffe-distri ---
[INFO] Executing tasks

protoc:
     [exec] make[1]: Entering directory `/home/student/CaffeOnSpark/caffe-distri'
     [exec] make[1]: Leaving directory`/home/student/CaffeOnSpark/caffe-distri'
     [exec] make[1]: **\* No rule to make target `../caffe-public/distribute/proto/caffe.proto', needed by`src/main/java/caffe/Caffe.java'.  Stop.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] caffe ............................................. SUCCESS [  0.003 s]
[INFO] caffe-distri ...................................... FAILURE [  3.580 s]
[INFO] caffe-grid ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.645 s
[INFO] Finished at: 2016-06-19T14:16:01+00:00
[INFO] Final Memory: 6M/18M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (proto) on project caffe-distri: An Ant BuildException has occured: exec returned: 2
[ERROR] around Ant part ...<exec dir="/home/student/CaffeOnSpark/caffe-distri" executable="make" failonerror="true">... @ 5:92 in /home/student/CaffeOnSpark/caffe-distri/target/antrun/build-protoc.xml

**Comment by anfeng** [comment]
<CaffeOnSpark>/caffe-public/distribute/proto/caffe.proto should be created
at caffe-public.

Please run "make build" from <CaffeOnSpark> folder.

Andy

**Comment by helloFromTheOtherSide** [comment]
Hello!
I was running "make build" from <CaffeOnSpark> folder. The error was in fact caused by not including python libraries folders in Makefile.config. 
But after included them, now i get the following error:

[INFO] Compiling 10 source files to /home/student/CaffeOnSpark/caffe-distri/target/classes
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (make) @ caffe-distri ---
[INFO] Executing tasks

make:
     [exec] make[1]: Entering directory `/home/student/CaffeOnSpark/caffe-distri'
     [exec] javah -d include/jni -force -cp target/classes \
     [exec] 	com.yahoo.ml.jcaffe.MatVector
     [exec] javah -d include/jni -force -cp target/classes \
     [exec] 	com.yahoo.ml.jcaffe.CaffeNet
     [exec] javah -d include/jni -force -cp target/classes \
     [exec] 	com.yahoo.ml.jcaffe.FloatDataTransformer
     [exec] javah -d include/jni -force -cp target/classes \
     [exec] 	com.yahoo.ml.jcaffe.Mat
     [exec] javah -d include/jni -force -cp target/classes \
     [exec] 	com.yahoo.ml.jcaffe.FloatBlob
     [exec] javah -d include/jni -force -cp target/classes \
     [exec] 	com.yahoo.ml.jcaffe.FloatArray
     [exec] make[1]: *** [.build_release/src/main/cpp/util/rdma.o] Error 1
     [exec] CXX src/main/cpp/util/rdma.cpp
     [exec] cc1plus: error: /usr/lib/jvm/java-7-oracle/bin/java/include: Not a directory
     [exec] cc1plus: error: /usr/lib/jvm/java-7-oracle/bin/java/include/linux: Not a directory
     **[exec] make[1]: *** [.build_release/src/main/cpp/util/rdma.o] Error 1
     [exec] CXX src/main/cpp/util/rdma.cpp
     [exec] cc1plus: error: /usr/lib/jvm/java-7-oracle/bin/java/include: Not a directory
     [exec] cc1plus: error: /usr/lib/jvm/java-7-oracle/bin/java/include/linux: Not a directory**
     [exec] make[1]: Leaving directory `/home/student/CaffeOnSpark/caffe-distri'

Can you tell me what this means ?

**Comment by arundasan91** [comment]
I know this is an old one, but hey. 

Were you able to get it working ?

If not please try these:

- Are you sure java is properly installed ? Do you have the proper `JAVA_HOME` set in your `.bashrc` file ? See if you have this in your `.bashrc` file:

    `export JAVA_HOME=/usr/lib/jvm/java-7-oracle`
   
    I use `java-7-openjdk-amd64`. To install it and check, run this:

    `sudo apt-get install openjdk-7-jdk`

    Don't forget to update `.bashrc` file if you are going to install `openjdk` version:

    `export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-amd64`

- Is `caffe` working ? Please install `caffe` and check if you can open a python terminal and `import caffe` properly. This will make sure that you don't have any dependency issues. 

- Make sure you have maven installed:
    `sudo apt-get install maven`

- Try going `sudo` whenever possible. Do `make clean` inside `CaffeOnSpark` root folder if you encounter errors.

- I sometimes forget to source the `.bashrc` file. Did you ? Please:
    `source ~/.bashrc`

Please let me know if it worked and close the Issue. If not, please update the situation.

**Comment by PHILO-HE** [comment]
Run make clean in the root folder of CaffeOnSpark. It works for me when I encountered the same problem.

**Comment by mriduljain** [comment]
No update. closing. reopen if required
