### ISSUE TITLE
Would you please provide cifar-10 training and testing data as example?

### ISSUE THREAD

**Issue by nhe150** [yahoo/CaffeOnSpark#9]
cifar-10 is a decent example to do benchmark on. At least it will take a minute to achieve 75% accuracy.

**Comment by junshi15** [comment]
BVLC caffe has scripts to download and generate cifar-10 lmdb files. They also provide prototxt files. Following the MNIST example,  you will need to change the input layers to memory layers.

**Comment by nhe150** [comment]
thanks.
