### ISSUE TITLE
An error about building

### ISSUE THREAD

**Issue by dahaichangge** [yahoo/CaffeOnSpark#90]
The error is ：

[INFO] Reactor Summary:
[INFO] 
[INFO] caffe .............................................. SUCCESS [  0.001 s]
[INFO] caffe-distri ....................................... FAILURE [  1.074 s]
[INFO] caffe-grid ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.364 s
[INFO] Finished at: 2016-06-20T10:13:29+08:00
[INFO] Final Memory: 39M/3926M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (proto) on project caffe-distri: An Ant BuildException has occured: exec returned: 2
[ERROR] around Ant part ...<exec dir="/home/liutao/CaffeOnSpark/caffe-distri" executable="make" failonerror="true">... @ 5:91 in /home/liutao/CaffeOnSpark/caffe-distri/target/antrun/build-protoc.xml
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :caffe-distri
Makefile:9: recipe for target 'build' failed
make: *** [build] Error 1
root@master:/home/liutao/CaffeOnSpark# mvn --version
Picked up _JAVA_OPTIONS: -Xms4g -Xmx32g

I would appreciate it if you could help me.

**Comment by junshi15** [comment]
unclear what the cause was since the error message was not very informative. Maybe installed protobuf was not version 2.5?

**Comment by mriduljain** [comment]
@dahaichangge If this is solved, please comment and close

**Comment by dahaichangge** [comment]
sorry，it did not work...

**Comment by mriduljain** [comment]
This that the only error. Please check the complete log or post it

**Comment by mriduljain** [comment]
What is the mvn version and protoc version you are using

**Comment by mriduljain** [comment]
protoc --version

**Comment by dahaichangge** [comment]
maven 3.3.3,protobufer 2.5.0

**Comment by mriduljain** [comment]
Is this fixed?

**Comment by dahaichangge** [comment]
my classmate modified and fixed it.

**Comment by mriduljain** [comment]
What was the problem? Others may find it helpful

**Comment by dahaichangge** [comment]
Modified configuration files and variables.He did not write a note...

**Comment by nzeng** [comment]
How to fix this error?
