### ISSUE TITLE
Build fails on error: "vector" has not declared

### ISSUE THREAD

**Issue by navjotk** [yahoo/CaffeOnSpark#92]
Hi I am trying to build this project on Ubuntu 16.04.
caffe-public builds with no errors
While trying to build caffe-distri, I face the following error:
```
In file included from ./include/util/MemoryInputAdapter.hpp:8:0,
                 from src/main/cpp/util/MemoryInputAdapter.cpp:4:
./include/util/InputAdapter.hpp:30:23: error: ‘vector’ has not been declared
     virtual void feed(vector< Blob<Dtype>* >&  dataBlobs, Dtype* labelPtr) = 0;

...<snipped>
```

The last executed command that led to this error was: 
```
CXX src/main/cpp/util/MemoryInputAdapter.cpp
g++ src/main/cpp/util/MemoryInputAdapter.cpp -fPIC -MMD -MP -pthread -fPIC -DDEBUG -g -O0 -DUSE_OPENCV -DCPU_ONLY -DUSE_MKL -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I/home/aluno/projects/caffe/CaffeOnSpark/caffe-public/include/caffe/ -I/usr/include/hdf5/serial -I/home/aluno/Downloads/leveldb-master/include -I/home/aluno/Downloads/opencv-2.4.10/include -I/include -I.build_debug/src -I./include -I../caffe-public/distribute/include -I../caffe-public/src -I/include/linux -I/opt/intel/mkl/include -Wall -Wno-sign-compare -c -o .build_debug/src/main/cpp/util/MemoryInputAdapter.o 2> .build_debug/src/main/cpp/util/MemoryInputAdapter.o.warnings.txt \
	|| (cat .build_debug/src/main/cpp/util/MemoryInputAdapter.o.warnings.txt; exit 1)
```

Can someone help me identify where this class vector is supposed to come from? What is this error related to, exactly?

**Comment by junshi15** [comment]
This is strange. "vector" is std::vector, which is declared here:
https://github.com/yahoo/caffe/blob/e107fb7a0d737868aff401ef954c1d8059e5e450/include/caffe/common.hpp#L94
and included by
https://github.com/yahoo/CaffeOnSpark/blob/master/caffe-distri/include/common.hpp
I am not sure why your compiler could not find it.

**Comment by mriduljain** [comment]
Do you see them under: ../caffe-public/distribute/include/caffe/
If so, there is a problem with the some path setting. Checkout the caffe-distri/Makefile and try to include in INCLUDE_DIRS with full path or something to check

**Comment by navjotk** [comment]
I was trying a non-standard install here, i.e. without internet access. Cleaning and repeating with internet access available made this error disappear. 

Can possibly be closed since I can't even reproduce this issue any more. 

Thanks for the help!

**Comment by junshi15** [comment]
Thanks for your update. I am closing the issue.
