### ISSUE TITLE
Is it possible to combine multiple .caffemodel into one?

### ISSUE THREAD

**Issue by stickFigure1235** [yahoo/CaffeOnSpark#96]
I want to be able to combine x.caffemodel with y.caffemodel. Is that possible and are there any existing examples of this?

Thanks.

**Comment by junshi15** [comment]
caffemodel files are protobuf files. You should be able to open/modify them with a protobuf tool.

**Comment by stickFigure1235** [comment]
What tool can I use to do that with?

**Comment by junshi15** [comment]
You can use Caffe python interface. 

An example is here:
https://github.com/yahoo/caffe/blob/e107fb7a0d737868aff401ef954c1d8059e5e450/examples/net_surgery.ipynb

Pay attention to "In [8]  # Load the fully convolutional network to transplant the parameters."

**Comment by mriduljain** [comment]
@stickFigure1235 If this is addressed, please close the bug
