### ISSUE TITLE
number of MNIST example test results varies

### ISSUE THREAD

**Issue by jsongcse** [yahoo/CaffeOnSpark#97]
Good afternoon. May I ask you a question?

After I ran the MNIST example, I found that the number of test data are different depending on the running environment. For example, when I ran CaffeOnSpark on the local mode of Spark, there were exactly 10000 test results when I typed `cat ${CAFFE_ON_SPARK}/lenet_features_result/*`. But in the cluster mode, on HDFS there were 9900 test results when I typed `hadoop fs -cat some/path/lenet_features_result/*`. What would be the reason?

Thank you for your help!

**Comment by junshi15** [comment]
This is due to the partition sizes indivisible by batch size, some of the samples get discarded as the remainder. In lenet_memory_train_test.prototxt, set the test batch size to 1 (the batch size in the test phase), then you should get the correct number of samples.

**Comment by mriduljain** [comment]
@jsongcse Please close this bug if it works for you

**Comment by jsongcse** [comment]
Thanks! I will close this issue.
